import { Product, ProductsTypes, ParentProducts } from '../models/product.model';

export var PRODUCTS: Product[] = [
    {
        id: 1,
        title: 'Resin BackFlow Fountain',
        details: 'fountain dhoop stand',
        imageSrc: 'assets/images/BackFlow Fountain/Resin Fountain/71UgC3RX5JL._SL1500_.jpg',
        isAddedToCart: false,
        productType: ProductsTypes.ResinFountain,
        isChild: true,
        parentProductType: ProductsTypes.BackFlowFountain,
    },
    {
        id: 2,
        title: 'Resin BackFlow Fountain',
        details: 'fountain dhoop stand',
        isAddedToCart: false,
        imageSrc: 'assets/images/BackFlow Fountain/Resin Fountain/71vTrBF1l1L._SL1258_.jpg',
        productType: ProductsTypes.ResinFountain,
        isChild: true,
        parentProductType: ProductsTypes.BackFlowFountain,
    },
    {
        id: 3,
        title: 'Resin BackFlow Fountain',
        details: 'fountain dhoop stand',
        isAddedToCart: false,
        imageSrc: 'assets/images/BackFlow Fountain/Resin Fountain/DSC06386.JPG',
        productType: ProductsTypes.ResinFountain,
        isChild: true,
        parentProductType: ProductsTypes.BackFlowFountain,
    },
    {
        id: 4,
        title: 'Resin BackFlow Fountain',
        isAddedToCart: false,
        details: 'fountain dhoop stand',
        imageSrc: 'assets/images/BackFlow Fountain/Resin Fountain/IMG-20180705-WA0008.jpg',
        productType: ProductsTypes.ResinFountain,
        isChild: true,
        parentProductType: ProductsTypes.BackFlowFountain,
    },
    {
        id: 5,
        title: 'Resin BackFlow Fountain',
        isAddedToCart: false,
        details: 'fountain dhoop stand',
        imageSrc: 'assets/images/BackFlow Fountain/Resin Fountain/IMG-20180705-WA0019.jpg',
        productType: ProductsTypes.ResinFountain,
        isChild: true,
        parentProductType: ProductsTypes.BackFlowFountain,
    },
    {
        id: 6,
        title: 'Resin BackFlow Fountain',
        details: 'fountain dhoop stand',
        isAddedToCart: false,
        imageSrc: 'assets/images/BackFlow Fountain/Resin Fountain/IMG-20180705-WA0022.jpg',
        productType: ProductsTypes.ResinFountain,
        isChild: true,
        parentProductType: ProductsTypes.BackFlowFountain,
    },
    {
        id: 7,
        title: 'Resin BackFlow Fountain',
        isAddedToCart: false,
        details: 'fountain dhoop stand',
        imageSrc: 'assets/images/BackFlow Fountain/Resin Fountain/IMG-20180705-WA0025.jpg',
        productType: ProductsTypes.ResinFountain,
        isChild: true,
        parentProductType: ProductsTypes.BackFlowFountain,
    },
    {
        id: 8,
        title: 'Resin BackFlow Fountain',
        isAddedToCart: false,
        details: 'fountain dhoop stand',
        imageSrc: 'assets/images/BackFlow Fountain/Resin Fountain/IMG-20180705-WA0027.jpg',
        productType: ProductsTypes.ResinFountain,
        isChild: true,
        parentProductType: ProductsTypes.BackFlowFountain,
    },
    {
        id: 9,
        title: 'Ceramic BackFlow Fountain',
        isAddedToCart: false,
        details: 'fountain dhoop stand',
        imageSrc: 'assets/images/BackFlow Fountain/Ceramic Fountain/IMG-20170907-WA0018.jpg',
        productType: ProductsTypes.CeramicFountain,
        isChild: true,
        parentProductType: ProductsTypes.BackFlowFountain,
    },
    {
        id: 10,
        title: 'Ceramic BackFlow Fountain',
        isAddedToCart: false,
        details: 'fountain dhoop stand',
        imageSrc: 'assets/images/BackFlow Fountain/Ceramic Fountain/PicsArt_06-14-03.25.56.jpg',
        productType: ProductsTypes.CeramicFountain,
        isChild: true,
        parentProductType: ProductsTypes.BackFlowFountain,
    },
    {
        id: 11,
        title: 'Ceramic BackFlow Fountain',
        isAddedToCart: false,
        details: 'fountain dhoop stand',
        imageSrc: 'assets/images/BackFlow Fountain/Ceramic Fountain/PicsArt_06-14-03.46.12.jpg',
        productType: ProductsTypes.CeramicFountain,
        isChild: true,
        parentProductType: ProductsTypes.BackFlowFountain,
    },
    {
        id: 12,
        title: 'Ceramic BackFlow Fountain',
        isAddedToCart: false,
        details: 'fountain dhoop stand',
        imageSrc: 'assets/images/BackFlow Fountain/Ceramic Fountain/PicsArt_06-14-04.14.39.jpg',
        productType: ProductsTypes.CeramicFountain,
        isChild: true,
        parentProductType: ProductsTypes.BackFlowFountain,
    },
    {
        id: 13,
        title: 'Ceramic BackFlow Fountain',
        isAddedToCart: false,
        details: 'fountain dhoop stand',
        imageSrc: 'assets/images/BackFlow Fountain/Ceramic Fountain/PicsArt_06-14-05.00.19.jpg',
        productType: ProductsTypes.CeramicFountain,
        isChild: true,
        parentProductType: ProductsTypes.BackFlowFountain,
    },
    {
        id: 14,
        title: 'Ceramic BackFlow Fountain',
        isAddedToCart: false,
        details: 'fountain dhoop stand',
        imageSrc: 'assets/images/BackFlow Fountain/Ceramic Fountain/PicsArt_06-14-05.28.57.jpg',
        productType: ProductsTypes.CeramicFountain,
        isChild: true,
        parentProductType: ProductsTypes.BackFlowFountain,
    },
    {
        id: 15,
        title: 'Ceramic BackFlow Fountain',
        isAddedToCart: false,
        details: 'fountain dhoop stand',
        imageSrc: 'assets/images/BackFlow Fountain/Ceramic Fountain/PicsArt_06-14-06.25.24.jpg',
        productType: ProductsTypes.CeramicFountain,
        isChild: true,
        parentProductType: ProductsTypes.BackFlowFountain,
    },
    {
        id: 16,
        title: 'Ceramic BackFlow Fountain',
        isAddedToCart: false,
        details: 'fountain dhoop stand',
        imageSrc: 'assets/images/BackFlow Fountain/Ceramic Fountain/PicsArt_06-14-06.51.36.jpg',
        productType: ProductsTypes.CeramicFountain,
        isChild: true,
        parentProductType: ProductsTypes.BackFlowFountain,
    },
    {
        id: 17,
        title: 'Ceramic BackFlow Fountain',
        isAddedToCart: false,
        details: 'fountain dhoop stand',
        imageSrc: 'assets/images/BackFlow Fountain/Ceramic Fountain/IMG-20200608-WA0018.jpg',
        productType: ProductsTypes.CeramicFountain,
        isChild: true,
        parentProductType: ProductsTypes.BackFlowFountain,
    },
    {
        id: 18,
        title: 'Ceramic BackFlow Fountain',
        isAddedToCart: false,
        details: 'fountain dhoop stand',
        imageSrc: 'assets/images/BackFlow Fountain/Ceramic Fountain/IMG-20200608-WA0018.jpg',
        productType: ProductsTypes.CeramicFountain,
        isChild: true,
        parentProductType: ProductsTypes.BackFlowFountain,
    },
    {
        id: 19,
        title: 'Ceramic BackFlow Fountain',
        isAddedToCart: false,
        details: 'fountain dhoop stand',
        imageSrc: 'assets/images/BackFlow Fountain/Ceramic Fountain/IMG-20200608-WA0018.jpg',
        productType: ProductsTypes.CeramicFountain,
        isChild: true,
        parentProductType: ProductsTypes.BackFlowFountain,
    },
    {
        id: 20,
        title: 'Cobra Stand',
        isAddedToCart: false,
        details: 'fountain dhoop stand',
        imageSrc: 'assets/images/Cobra Stand/Cobra stand 2 Inc.jpg',
        productType: ProductsTypes.CobraStand,
        isChild: false,
        parentProductType: ProductsTypes.CobraStand,
    },
    {
        id: 21,
        title: 'Copper Bottles',
        isAddedToCart: false,
        details: 'Copper Water Bottles',
        imageSrc: 'assets/images/Copper Bottles/BS-CV- -04- Diammond.png',
        productType: ProductsTypes.CopperBottle,
        isChild: false,
        parentProductType: ProductsTypes.CopperBottle,
    },
    {
        id: 22,
        title: 'Copper Bottles',
        isAddedToCart: false,
        details: 'Copper Water Bottles',
        imageSrc: 'assets/images/Copper Bottles/BS-CV-03 Hammed.png',
        productType: ProductsTypes.CopperBottle,
        isChild: false,
        parentProductType: ProductsTypes.CopperBottle,
    },
    {
        id: 23,
        title: 'Copper Bottles',
        isAddedToCart: false,
        details: 'Copper Water Bottles',
        imageSrc: 'assets/images/Copper Bottles/BS-CV-05 printed.png',
        productType: ProductsTypes.CopperBottle,
        isChild: false,
        parentProductType: ProductsTypes.CopperBottle,
    },
    {
        id: 24,
        title: 'Copper Bottles',
        isAddedToCart: false,
        details: 'Copper Water Bottles',
        imageSrc: 'assets/images/Copper Bottles/BS-CV-06 Printed.png',
        productType: ProductsTypes.CopperBottle,
        isChild: false,
        parentProductType: ProductsTypes.CopperBottle,
    },
    {
        id: 25,
        title: 'Copper Bottles',
        isAddedToCart: false,
        details: 'Copper Water Bottles',
        imageSrc: 'assets/images/Copper Bottles/BS-CV-07 Printed.png',
        productType: ProductsTypes.CopperBottle,
        isChild: false,
        parentProductType: ProductsTypes.CopperBottle,
    },
    {
        id: 26,
        title: 'Copper Bottles',
        isAddedToCart: false,
        details: 'Copper Water Bottles',
        imageSrc: 'assets/images/Copper Bottles/BS-CV-08 Printed.jpg',
        productType: ProductsTypes.CopperBottle,
        isChild: false,
        parentProductType: ProductsTypes.CopperBottle,
    },
    {
        id: 27,
        title: 'Copper Bottles',
        isAddedToCart: false,
        details: 'Copper Water Bottles',
        imageSrc: 'assets/images/Copper Bottles/BS-CV-09 printed.jpg',
        productType: ProductsTypes.CopperBottle,
        isChild: false,
        parentProductType: ProductsTypes.CopperBottle,
    },
    {
        id: 28,
        title: 'Copper Bottles',
        isAddedToCart: false,
        details: 'Copper Water Bottles',
        imageSrc: 'assets/images/Copper Bottles/BS-CV-10 Printed.jpg',
        productType: ProductsTypes.CopperBottle,
        isChild: false,
        parentProductType: ProductsTypes.CopperBottle,
    },
    {
        id: 29,
        title: 'Copper Bottles',
        isAddedToCart: false,
        details: 'Copper Water Bottles',
        imageSrc: 'assets/images/Copper Bottles/BS-CV-11 Printed.jpg',
        productType: ProductsTypes.CopperBottle,
        isChild: false,
        parentProductType: ProductsTypes.CopperBottle,
    },
    {
        id: 30,
        title: ' Incense Holder',
        isAddedToCart: false,
        details: 'Brass Incense Holder',
        imageSrc: 'assets/images/incense holder/Brass Incense Holder/Brh-1.JPG',
        productType: ProductsTypes.BrassIncenseHolder,
        isChild: true,
        parentProductType: ProductsTypes.IncenseHolder,
    },
    {
        id: 31,
        title: ' Incense Holder',
        isAddedToCart: false,
        details: 'Brass Incense Holder',
        imageSrc: 'assets/images/incense holder/Brass Incense Holder/BRH-02.jpg',
        productType: ProductsTypes.BrassIncenseHolder,
        isChild: true,
        parentProductType: ProductsTypes.IncenseHolder,
    },
    {
        id: 32,
        title: ' Incense Holder',
        isAddedToCart: false,
        details: 'Brass Incense Holder',
        imageSrc: 'assets/images/incense holder/Brass Incense Holder/brh-5.jpg',
        productType: ProductsTypes.BrassIncenseHolder,
        isChild: true,
        parentProductType: ProductsTypes.IncenseHolder,
    },
    {
        id: 33,
        title: ' Incense Holder',
        isAddedToCart: false,
        details: 'Ceramic Incense Holder',
        imageSrc: 'assets/images/incense holder/Ceramic Incense Holder/IMG-20200608-WA0029.jpg',
        productType: ProductsTypes.CeramicIncenseHolder,
        isChild: true,
        parentProductType: ProductsTypes.IncenseHolder,
    },
    {
        id: 34,
        title: ' Incense Holder',
        isAddedToCart: false,
        details: 'Ceramic Incense Holder',
        imageSrc: 'assets/images/incense holder/Ceramic Incense Holder/IMG-20200608-WA0030.jpg',
        productType: ProductsTypes.CeramicIncenseHolder,
        isChild: true,
        parentProductType: ProductsTypes.IncenseHolder,
    },
    {
        id: 35,
        title: ' Incense Holder',
        isAddedToCart: false,
        details: 'Ceramic Incense Holder',
        imageSrc: 'assets/images/incense holder/Ceramic Incense Holder/IMG-20200608-WA0031.jpg',
        productType: ProductsTypes.CeramicIncenseHolder,
        isChild: true,
        parentProductType: ProductsTypes.IncenseHolder,
    },
    {
        id: 36,
        title: ' Incense Holder',
        isAddedToCart: false,
        details: 'Metal Incense Holder',
        imageSrc: 'assets/images/incense holder/Metal Incense Holder/AIH-1010.JPG',
        productType: ProductsTypes.MetalIncenseHolder,
        isChild: true,
        parentProductType: ProductsTypes.IncenseHolder,
    },
    {
        id: 37,
        title: ' Incense Holder',
        isAddedToCart: false,
        details: 'Metal Incense Holder',
        imageSrc: 'assets/images/incense holder/Metal Incense Holder/ALH-1009.jpg',
        productType: ProductsTypes.MetalIncenseHolder,
        isChild: true,
        parentProductType: ProductsTypes.IncenseHolder,
    },
    {
        id: 38,
        title: ' Incense Holder',
        isAddedToCart: false,
        details: 'Metal Incense Holder',
        imageSrc: 'assets/images/incense holder/Metal Incense Holder/ALH-1010.JPG',
        productType: ProductsTypes.MetalIncenseHolder,
        isChild: true,
        parentProductType: ProductsTypes.IncenseHolder,
    },
    {
        id: 39,
        title: ' Incense Holder',
        isAddedToCart: false,
        details: 'Metal Incense Holder',
        imageSrc: 'assets/images/incense holder/Metal Incense Holder/IMG_20191010_141854.jpg',
        productType: ProductsTypes.MetalIncenseHolder,
        isChild: true,
        parentProductType: ProductsTypes.IncenseHolder,
    },
    {
        id: 40,
        title: ' Incense Holder',
        isAddedToCart: false,
        details: 'Metal Incense Holder',
        imageSrc: 'assets/images/incense holder/Metal Incense Holder/IMG_20191010_141943.jpg',
        productType: ProductsTypes.MetalIncenseHolder,
        isChild: true,
        parentProductType: ProductsTypes.IncenseHolder,
    },
    {
        id: 41,
        title: ' Incense Holder',
        isAddedToCart: false,
        details: 'Metal Incense Holder',
        imageSrc: 'assets/images/incense holder/Metal Incense Holder/WMIH-35A.jpg',
        productType: ProductsTypes.MetalIncenseHolder,
        isChild: true,
        parentProductType: ProductsTypes.IncenseHolder,
    },
    {
        id: 42,
        title: ' Incense Holder',
        isAddedToCart: false,
        details: 'Metal Incense Holder',
        imageSrc: 'assets/images/incense holder/Metal Incense Holder/WMIH-35Ca.jpg',
        productType: ProductsTypes.MetalIncenseHolder,
        isChild: true,
        parentProductType: ProductsTypes.IncenseHolder,
    },
    {
        id: 43,
        title: ' Incense Holder',
        isAddedToCart: false,
        details: 'Paper Mache Incense Holder',
        imageSrc: 'assets/images/incense holder/Paper Mache Incense holder/PMSH-06.jpg',
        productType: ProductsTypes.PaperMacheIncenseHolder,
        isChild: true,
        parentProductType: ProductsTypes.IncenseHolder,
    },
    {
        id: 44,
        title: ' Incense Holder',
        isAddedToCart: false,
        details: 'Paper Mache Incense Holder',
        imageSrc: 'assets/images/incense holder/Paper Mache Incense holder/PMSH-11.JPG',
        productType: ProductsTypes.PaperMacheIncenseHolder,
        isChild: true,
        parentProductType: ProductsTypes.IncenseHolder,
    },
    {
        id: 45,
        title: ' Incense Holder',
        isAddedToCart: false,
        details: 'Paper Mache Incense Holder',
        imageSrc: 'assets/images/incense holder/Paper Mache Incense holder/PMSH-12JPEG.jpg',
        productType: ProductsTypes.PaperMacheIncenseHolder,
        isChild: true,
        parentProductType: ProductsTypes.IncenseHolder,
    },
    {
        id: 46,
        title: ' Incense Holder',
        isAddedToCart: false,
        details: 'Wooden Incense Holder',
        imageSrc: 'assets/images/incense holder/Wooden Incense Holder/Colour Ins.Holder.JPG',
        productType: ProductsTypes.WoodenIncenseHolder,
        isChild: true,
        parentProductType: ProductsTypes.IncenseHolder,
    },
    {
        id: 47,
        title: ' Incense Holder',
        isAddedToCart: false,
        details: 'Wooden Incense Holder',
        imageSrc: 'assets/images/incense holder/Wooden Incense Holder/WCB-01.jpg',
        productType: ProductsTypes.WoodenIncenseHolder,
        isChild: true,
        parentProductType: ProductsTypes.IncenseHolder,
    },
    {
        id: 48,
        title: ' Incense Holder',
        isAddedToCart: false,
        details: 'Wooden Incense Holder',
        imageSrc: 'assets/images/incense holder/Wooden Incense Holder/WH-227.JPG',
        productType: ProductsTypes.WoodenIncenseHolder,
        isChild: true,
        parentProductType: ProductsTypes.IncenseHolder,
    },
    {
        id: 49,
        title: ' Incense Holder',
        isAddedToCart: false,
        details: 'Wooden Incense Holder',
        imageSrc: 'assets/images/incense holder/Wooden Incense Holder/WH-230.JPG',
        productType: ProductsTypes.WoodenIncenseHolder,
        isChild: true,
        parentProductType: ProductsTypes.IncenseHolder,
    },
    {
        id: 50,
        title: ' Incense Holder',
        isAddedToCart: false,
        details: 'Wooden Incense Holder',
        imageSrc: 'assets/images/incense holder/Wooden Incense Holder/WHC-02.jpg',
        productType: ProductsTypes.WoodenIncenseHolder,
        isChild: true,
        parentProductType: ProductsTypes.IncenseHolder,
    },
    {
        id: 51,
        title: ' Incense Holder',
        isAddedToCart: false,
        details: 'Wooden Incense Holder',
        imageSrc: 'assets/images/incense holder/Wooden Incense Holder/WHC-05.jpg',
        productType: ProductsTypes.WoodenIncenseHolder,
        isChild: true,
        parentProductType: ProductsTypes.IncenseHolder,
    },
    {
        id: 52,
        title: ' Incense Holder',
        isAddedToCart: false,
        details: 'Wooden Incense Holder',
        imageSrc: 'assets/images/incense holder/Wooden Incense Holder/WHC-06.jpg',
        productType: ProductsTypes.WoodenIncenseHolder,
        isChild: true,
        parentProductType: ProductsTypes.IncenseHolder,
    },
    {
        id: 53,
        title: ' Incense Holder',
        isAddedToCart: false,
        details: 'Wooden Incense Holder',
        imageSrc: 'assets/images/incense holder/Wooden Incense Holder/WIB-501.jpg',
        productType: ProductsTypes.WoodenIncenseHolder,
        isChild: true,
        parentProductType: ProductsTypes.IncenseHolder,
    },
    {
        id: 54,
        title: ' Incense Holder',
        isAddedToCart: false,
        details: 'Wooden Incense Holder',
        imageSrc: 'assets/images/incense holder/Wooden Incense Holder/WIB-502.jpg',
        productType: ProductsTypes.WoodenIncenseHolder,
        isChild: true,
        parentProductType: ProductsTypes.IncenseHolder,
    },
    {
        id: 55,
        title: ' Incense Holder',
        isAddedToCart: false,
        details: 'Wooden Incense Holder',
        imageSrc: 'assets/images/incense holder/Wooden Incense Holder/WIB-503.jpg',
        productType: ProductsTypes.WoodenIncenseHolder,
        isChild: true,
        parentProductType: ProductsTypes.IncenseHolder,
    },
    {
        id: 56,
        title: ' Incense Holder',
        isAddedToCart: false,
        details: 'Wooden Incense Holder',
        imageSrc: 'assets/images/incense holder/Wooden Incense Holder/WIB-504.jpg',
        productType: ProductsTypes.WoodenIncenseHolder,
        isChild: true,
        parentProductType: ProductsTypes.IncenseHolder,
    },
    {
        id: 57,
        title: ' Incense Holder',
        isAddedToCart: false,
        details: 'Wooden Incense Holder',
        imageSrc:
            'assets/images/incense holder/Wooden Incense Holder/Wooden  Ins  Holder- WIH- C-03 Red.jpg',
        productType: ProductsTypes.WoodenIncenseHolder,
        isChild: true,
        parentProductType: ProductsTypes.IncenseHolder,
    },
    {
        id: 58,
        title: ' Incense Holder',
        isAddedToCart: false,
        details: 'Wooden Incense Holder',
        imageSrc:
            'assets/images/incense holder/Wooden Incense Holder/Wooden  Ins  Holder- WIH- C-03 Y.jpg',
        productType: ProductsTypes.WoodenIncenseHolder,
        isChild: true,
        parentProductType: ProductsTypes.IncenseHolder,
    },
    {
        id: 59,
        title: ' Incense Holder',
        isAddedToCart: false,
        details: 'Wooden Incense Holder',
        imageSrc:
            'assets/images/incense holder/Wooden Incense Holder/Wooden  Ins Boxr- WIB C-01.jpg',
        productType: ProductsTypes.WoodenIncenseHolder,
        isChild: true,
        parentProductType: ProductsTypes.IncenseHolder,
    },
    {
        id: 60,
        title: ' Incense Holder',
        isAddedToCart: false,
        details: 'Wooden Incense Holder',
        imageSrc:
            'assets/images/incense holder/Wooden Incense Holder/Wooden  Ins Boxr- WIB C-02.jpg',
        productType: ProductsTypes.WoodenIncenseHolder,
        isChild: true,
        parentProductType: ProductsTypes.IncenseHolder,
    },
    {
        id: 61,
        title: ' Oil Burner',
        isAddedToCart: false,
        details: 'Brass Oil Burner',
        imageSrc: 'assets/images/oil burner/Brass Oil Burner/BBA-10.JPG',
        productType: ProductsTypes.BrassOilBurner,
        isChild: true,
        parentProductType: ProductsTypes.OilBurner,
    },
    {
        id: 61,
        title: ' Oil Burner',
        isAddedToCart: false,
        details: 'Soft Stone Oil Burner',
        imageSrc: 'assets/images/oil burner/Soft Stone Oil Burner/BS-O1.JPG',
        productType: ProductsTypes.SoftStoneOilBurner,
        isChild: true,
        parentProductType: ProductsTypes.OilBurner,
    },
    {
        id: 62,
        title: ' Oil Burner',
        isAddedToCart: false,
        details: 'Soft Stone Oil Burner',
        imageSrc: 'assets/images/oil burner/Soft Stone Oil Burner/BS-OB-02.JPG',
        productType: ProductsTypes.SoftStoneOilBurner,
        isChild: true,
        parentProductType: ProductsTypes.OilBurner,
    },
    {
        id: 63,
        title: ' Oil Burner',
        isAddedToCart: false,
        details: 'Soft Stone Oil Burner',
        imageSrc: 'assets/images/oil burner/Soft Stone Oil Burner/BS-OB45.JPG',
        productType: ProductsTypes.SoftStoneOilBurner,
        isChild: true,
        parentProductType: ProductsTypes.OilBurner,
    },
    {
        id: 64,
        title: ' Oil Burner',
        isAddedToCart: false,
        details: 'Soft Stone Oil Burner',
        imageSrc: 'assets/images/oil burner/Soft Stone Oil Burner/BS-OB50.JPG',
        productType: ProductsTypes.SoftStoneOilBurner,
        isChild: true,
        parentProductType: ProductsTypes.OilBurner,
    },
    {
        id: 65,
        title: ' Oil Burner',
        isAddedToCart: false,
        details: 'Soft Stone Oil Burner',
        imageSrc: 'assets/images/oil burner/Soft Stone Oil Burner/BS-OB51.JPG',
        productType: ProductsTypes.SoftStoneOilBurner,
        isChild: true,
        parentProductType: ProductsTypes.OilBurner,
    },
    {
        id: 66,
        title: ' Oil Burner',
        isAddedToCart: false,
        details: 'Soft Stone Oil Burner',
        imageSrc: 'assets/images/oil burner/Soft Stone Oil Burner/L-052.jpg',
        productType: ProductsTypes.SoftStoneOilBurner,
        isChild: true,
        parentProductType: ProductsTypes.OilBurner,
    },
    {
        id: 67,
        title: ' Oil Burner',
        isAddedToCart: false,
        details: 'Soft Stone Oil Burner',
        imageSrc: 'assets/images/oil burner/Soft Stone Oil Burner/L-053-10.jpg',
        productType: ProductsTypes.SoftStoneOilBurner,
        isChild: true,
        parentProductType: ProductsTypes.OilBurner,
    },
    {
        id: 68,
        title: ' Oil Burner',
        isAddedToCart: false,
        details: 'Soft Stone Oil Burner',
        imageSrc: 'assets/images/oil burner/Soft Stone Oil Burner/L-53-11.jpg',
        productType: ProductsTypes.SoftStoneOilBurner,
        isChild: true,
        parentProductType: ProductsTypes.OilBurner,
    },
    {
        id: 69,
        title: ' Oil Burner',
        isAddedToCart: false,
        details: 'Soft Stone Oil Burner',
        imageSrc: 'assets/images/oil burner/Soft Stone Oil Burner/L-054-7.jpg',
        productType: ProductsTypes.SoftStoneOilBurner,
        isChild: true,
        parentProductType: ProductsTypes.OilBurner,
    },
    {
        id: 70,
        title: ' Resin Burner',
        isAddedToCart: false,
        details: 'Brass Resin Burner',
        imageSrc: 'assets/images/Resin Burner/Brass Resin Burner/1114.jpg',
        productType: ProductsTypes.BrassResinBurner,
        isChild: true,
        parentProductType: ProductsTypes.ResinBurner,
    },
    {
        id: 71,
        title: ' Resin Burner',
        isAddedToCart: false,
        details: 'Brass Resin Burner',
        imageSrc: 'assets/images/Resin Burner/Brass Resin Burner/BRB-03 Blue.jpg',
        productType: ProductsTypes.BrassResinBurner,
        isChild: true,
        parentProductType: ProductsTypes.ResinBurner,
    },
    {
        id: 72,
        title: ' Resin Burner',
        isAddedToCart: false,
        details: 'Brass Resin Burner',
        imageSrc: 'assets/images/Resin Burner/Brass Resin Burner/BRB-03G.jpg',
        productType: ProductsTypes.BrassResinBurner,
        isChild: true,
        parentProductType: ProductsTypes.ResinBurner,
    },
    {
        id: 73,
        title: ' Resin Burner',
        isAddedToCart: false,
        details: 'Brass Resin Burner',
        imageSrc: 'assets/images/Resin Burner/Brass Resin Burner/BRB-03R.jpg',
        productType: ProductsTypes.BrassResinBurner,
        isChild: true,
        parentProductType: ProductsTypes.ResinBurner,
    },
    {
        id: 74,
        title: ' Resin Burner',
        isAddedToCart: false,
        details: 'Brass Resin Burner',
        imageSrc: 'assets/images/Resin Burner/Brass Resin Burner/BRB-03T.jpg',
        productType: ProductsTypes.BrassResinBurner,
        isChild: true,
        parentProductType: ProductsTypes.ResinBurner,
    },
    {
        id: 75,
        title: ' Resin Burner',
        isAddedToCart: false,
        details: 'Brass Resin Burner',
        imageSrc:
            'assets/images/Resin Burner/Brass Resin Burner/BRB-101-Pentagram  Carved Charcoal Burner.JPG',
        productType: ProductsTypes.BrassResinBurner,
        isChild: true,
        parentProductType: ProductsTypes.ResinBurner,
    },
    {
        id: 76,
        title: ' Resin Burner',
        isAddedToCart: false,
        details: 'Brass Resin Burner',
        imageSrc:
            'assets/images/Resin Burner/Brass Resin Burner/BRB-102Triple Moon Carved Charcoal Burner.JPG',
        productType: ProductsTypes.BrassResinBurner,
        isChild: true,
        parentProductType: ProductsTypes.ResinBurner,
    },
    {
        id: 77,
        title: ' Resin Burner',
        isAddedToCart: false,
        details: 'Brass Resin Burner',
        imageSrc: 'assets/images/Resin Burner/Brass Resin Burner/BRB03B.jpg',
        productType: ProductsTypes.BrassResinBurner,
        isChild: true,
        parentProductType: ProductsTypes.ResinBurner,
    },
    {
        id: 78,
        title: 'Tarot Box',
        isAddedToCart: false,
        details: 'Tarot Box',
        imageSrc: 'assets/images/Tarot Box/BOX-03a.JPG',
        productType: ProductsTypes.TarotBox,
        isChild: false,
        parentProductType: ProductsTypes.TarotBox,
    },
    {
        id: 79,
        title: 'Tarot Box',
        isAddedToCart: false,
        details: 'Tarot Box',
        imageSrc: 'assets/images/Tarot Box/RCI -01.jpg',
        productType: ProductsTypes.TarotBox,
        isChild: false,
        parentProductType: ProductsTypes.TarotBox,
    },
    {
        id: 80,
        title: 'Tarot Box',
        isAddedToCart: false,
        details: 'Tarot Box',
        imageSrc: 'assets/images/Tarot Box/RCI-02.jpg',
        productType: ProductsTypes.TarotBox,
        isChild: false,
        parentProductType: ProductsTypes.TarotBox,
    },
    {
        id: 81,
        title: 'Tarot Box',
        isAddedToCart: false,
        details: 'Tarot Box',
        imageSrc: 'assets/images/Tarot Box/RCI-03.jpg',
        productType: ProductsTypes.TarotBox,
        isChild: false,
        parentProductType: ProductsTypes.TarotBox,
    },
    {
        id: 82,
        title: 'Tarot Box',
        isAddedToCart: false,
        details: 'Tarot Box',
        imageSrc: 'assets/images/Tarot Box/RCI-04.jpg',
        productType: ProductsTypes.TarotBox,
        isChild: false,
        parentProductType: ProductsTypes.TarotBox,
    },
    {
        id: 83,
        title: 'Tarot Box',
        isAddedToCart: false,
        details: 'Tarot Box',
        imageSrc: 'assets/images/Tarot Box/Tarot Box.jpg',
        productType: ProductsTypes.TarotBox,
        isChild: false,
        parentProductType: ProductsTypes.TarotBox,
    },
    // {
    //     id: 84,
    //     title: 'Tarot Box',isAddedToCart:false,
    //     details:  'Tarot Box',
    //     imageSrc: 'assets/images/Tarot Box/Tree of Life.tiff',
    //     productType:ProductsTypes.TarotBox,isChild:false,parentProductType:ProductsTypes.ResinBurner,
    // },
];


export var PARENTPRODUCTSTYPES: ParentProducts[] = [
    { title: "Backflow fountain", parentProductType: ProductsTypes.BackFlowFountain },
    { title: "Incense Holder", parentProductType: ProductsTypes.IncenseHolder},
    { title: "Oil Burner", parentProductType: ProductsTypes.OilBurner},
    { title: "Resin Burner", parentProductType: ProductsTypes.ResinBurner},
    { title: "Cobra Stand", parentProductType: ProductsTypes.CobraStand},
    { title: "Tarot Box", parentProductType: ProductsTypes.TarotBox},
    { title: "Copper Bottles", parentProductType: ProductsTypes.CopperBottle},
]

export var CHILDPRODUCTSTYPES: ParentProducts[] = [
    { title: "Resinn fntn", parentProductType: ProductsTypes.ResinFountain},
    { title: "Ceramixx fntn", parentProductType: ProductsTypes.CeramicFountain },
    
]