import { Product, ProductsTypes, ParentProducts } from '../models/product.model';
import { title } from 'process';

export var PRODUCTS: ParentProducts[] = [
    {
        pageTitle: 'BackFlow Fountain',
        pageProductType: ProductsTypes.BackFlowFountain,
        children: [
            {
                childTitle: ' Resin BackFlow Fountain',
                childProducts: [
                    {
                        id: 1,
                        title: 'Resin BackFlow Fountain',
                        details: 'Resin BackFlow Fountain: RBF',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/BackFlow Fountain/Resin Fountain/71UgC3RX5JL._SL1500_.jpg',
                        productType: ProductsTypes.ResinFountain,
                    },
                    {
                        id: 2,
                        title: 'Resin BackFlow Fountain',
                        details: 'Resin BackFlow Fountain: RBF',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/BackFlow Fountain/Resin Fountain/71vTrBF1l1L._SL1258_.jpg',
                        productType: ProductsTypes.ResinFountain,
                    },
                    {
                        id: 3,
                        title: 'Resin BackFlow Fountain',
                        details: 'Resin BackFlow Fountain: RBF',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/BackFlow Fountain/Resin Fountain/DSC06386.JPG',
                        productType: ProductsTypes.ResinFountain,
                    },
                    {
                        id: 4,
                        title: 'Resin BackFlow Fountain',
                        details: 'Resin BackFlow Fountain: RBF',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/BackFlow Fountain/Resin Fountain/IMG-20180705-WA0008.jpg',
                        productType: ProductsTypes.ResinFountain,
                    },
                    {
                        id: 5,
                        title: 'Resin BackFlow Fountain',
                        details: 'Resin BackFlow Fountain: RBF',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/BackFlow Fountain/Resin Fountain/IMG-20180705-WA0019.jpg',
                        productType: ProductsTypes.ResinFountain,
                    },
                    {
                        id: 6,
                        title: 'Resin BackFlow Fountain',
                        details: 'Resin BackFlow Fountain: RBF',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/BackFlow Fountain/Resin Fountain/IMG-20180705-WA0022.jpg',
                        productType: ProductsTypes.ResinFountain,
                    },
                    {
                        id: 7,
                        title: 'Resin BackFlow Fountain',
                        details: 'Resin BackFlow Fountain: RBF',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/BackFlow Fountain/Resin Fountain/IMG-20180705-WA0025.jpg',
                        productType: ProductsTypes.ResinFountain,
                    },
                    {
                        id: 8,
                        title: 'Resin BackFlow Fountain',
                        details: 'Resin BackFlow Fountain: RBF',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/BackFlow Fountain/Resin Fountain/IMG-20180705-WA0027.jpg',
                        productType: ProductsTypes.ResinFountain,
                    },
                ]
            },
            {
                childTitle: 'Ceramic BackFlow Fountain',
                childProducts: [
                    {
                        id: 1,
                        title: 'Ceramic BackFlow Fountain',
                        details: 'Ceramic BackFlow Fountain: CBF',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/BackFlow Fountain/Ceramic Fountain/IMG-20170907-WA0018 .jpg',
                        productType: ProductsTypes.CeramicFountain,
                    },
                    {
                        id: 2,
                        title: 'Ceramic BackFlow Fountain',
                        details: 'Ceramic BackFlow Fountain: CBF',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/BackFlow Fountain/Ceramic Fountain/PicsArt_06-14-03.25.56.jpg',
                        productType: ProductsTypes.CeramicFountain,
                    },
                    {
                        id: 3,
                        title: 'Ceramic BackFlow Fountain',
                        details: 'Ceramic BackFlow Fountain: CBF',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/BackFlow Fountain/Ceramic Fountain/PicsArt_06-14-03.46.12.jpg',
                        productType: ProductsTypes.CeramicFountain,
                    },
                    {
                        id: 4,
                        title: 'Ceramic BackFlow Fountain',
                        details: 'Ceramic BackFlow Fountain: CBF',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/BackFlow Fountain/Ceramic Fountain/PicsArt_06-14-04.14.39.jpg',
                        productType: ProductsTypes.CeramicFountain,
                    },
                    {
                        id: 5,
                        title: ' Ceramic BackFlow Fountain',
                        details: 'Ceramic BackFlow Fountain: CBF',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/BackFlow Fountain/Ceramic Fountain/PicsArt_06-14-05.00.19.jpg',
                        productType: ProductsTypes.CeramicFountain,
                    },
                    {
                        id: 6,
                        title: 'Ceramic BackFlow Fountain',
                        details: 'Ceramic BackFlow Fountain: CBF',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/BackFlow Fountain/Ceramic Fountain/PicsArt_06-14-05.28.57.jpg',
                        productType: ProductsTypes.CeramicFountain,
                    },
                    {
                        id: 7,
                        title: 'Ceramic BackFlow Fountain',
                        details: 'Ceramic BackFlow Fountain: CBF',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/BackFlow Fountain/Ceramic Fountain/PicsArt_06-14-06.25.24.jpg',
                        productType: ProductsTypes.CeramicFountain,
                    },
                    {
                        id: 8,
                        title: 'Ceramic BackFlow Fountain',
                        details: 'Ceramic BackFlow Fountain: CBF',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/BackFlow Fountain/Ceramic Fountain/PicsArt_06-14-06.51.36.jpg',
                        productType: ProductsTypes.CeramicFountain,
                    },
                    {
                        id: 9,
                        title: 'Ceramic BackFlow Fountain',
                        details: 'Ceramic BackFlow Fountain: CBF',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/BackFlow Fountain/Ceramic Fountain/IMG_20200614_180748.jpg',
                        productType: ProductsTypes.CeramicFountain,
                    },
                    {
                        id: 10,
                        title: 'Ceramic BackFlow Fountain',
                        details: 'Ceramic BackFlow Fountain: CBF',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/BackFlow Fountain/Ceramic Fountain/PicsArt_06-14-08.44.10.jpg',
                        productType: ProductsTypes.CeramicFountain,
                    },
                    {
                        id: 11,
                        title: 'Ceramic BackFlow Fountain',
                        details: 'Ceramic BackFlow Fountain: CBF',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/BackFlow Fountain/Ceramic Fountain/PicsArt_06-14-09.52.51.jpg',
                        productType: ProductsTypes.CeramicFountain,
                    }

                ]
            }
        ]
    },
    {
        pageTitle: 'Cobra Stand',
        pageProductType: ProductsTypes.CobraStand,
        children: [
            {
                childTitle: 'Cobra Stand',
                childProducts: [

                    {
                        id: 1,
                        title: 'Cobra Stand',
                        details: 'Cobra stand: CS',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/Cobra Stand/Cobra stand 2 Inc.jpg',
                        productType: ProductsTypes.CobraStand,
                    },
                ]
            }
        ]
    },
    {
        pageTitle: 'Copper Bottle',
        pageProductType: ProductsTypes.CopperBottle,
        children: [
            {
                childTitle: 'Copper Bottles',
                childProducts: [

                    {
                        id: 1,
                        title: 'Copper Bottles',
                        details: 'Copper WaterBottles: CWB',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/Copper Bottles/BS-CV-04- Diammond .png',
                        productType: ProductsTypes.CopperBottle,
                    },
                    {
                        id: 2,
                        title: 'Copper Bottles',
                        details: 'Copper WaterBottles: CWB',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/Copper Bottles/BS-CV-03 Hammed.png',
                        productType: ProductsTypes.CopperBottle,
                    },
                    {
                        id: 3,
                        title: 'Copper Bottles',
                        details: 'Copper WaterBottles: CWB',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/Copper Bottles/BS-CV-05 printed.png',
                        productType: ProductsTypes.CopperBottle,
                    },
                    {
                        id: 4,
                        title: 'Copper Bottles',
                        details: 'Copper WaterBottles: CWB',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/Copper Bottles/BS-CV-06 Printed.png',
                        productType: ProductsTypes.CopperBottle,
                    },
                    {
                        id: 5,
                        title: 'Copper Bottles',
                        details: 'Copper WaterBottles: CWB',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/Copper Bottles/BS-CV-07 Printed.png',
                        productType: ProductsTypes.CopperBottle,
                    },
                    {
                        id: 6,
                        title: 'Copper Bottles',
                        details: 'Copper WaterBottles: CWB',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/Copper Bottles/BS-CV-08 Printed.jpg',
                        productType: ProductsTypes.CopperBottle,
                    },
                    {
                        id: 7,
                        title: 'Copper Bottles',
                        details: 'Copper WaterBottles: CWB',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/Copper Bottles/BS-CV-09 printed.jpg',
                        productType: ProductsTypes.CopperBottle,
                    },
                    {
                        id: 8,
                        title: 'Copper Bottles',
                        details: 'Copper WaterBottles: CWB',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/Copper Bottles/BS-CV-10 Printed.jpg',
                        productType: ProductsTypes.CopperBottle,
                    },
                    {
                        id: 9,
                        title: 'Copper Bottles',
                        details: 'Copper WaterBottles: CWB',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/Copper Bottles/BS-CV-11 Printed.jpg',
                        productType: ProductsTypes.CopperBottle,
                    },
                ]
            }
        ]
    },

    {
        pageTitle: 'Incense Stand',
        pageProductType: ProductsTypes.IncenseHolder,
        children: [
            {
                childTitle: 'Brass Incense Stand',
                childProducts: [
                    {
                        id: 1,
                        title: ' Brass Incense Stand',
                        details: 'Brass Incense Stand: BIS',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/incense holder/Brass Incense Holder/Brh-1.JPG',
                        productType: ProductsTypes.BrassIncenseHolder,
                    },
                    {
                        id: 2,
                        title: ' Brass Incense Stand',
                        details: 'Brass Incense Stand: BIS',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/incense holder/Brass Incense Holder/BRH-02.jpg',
                        productType: ProductsTypes.BrassIncenseHolder,
                    },
                    {
                        id: 3,
                        title: ' Brass Incense Stand',
                        details: 'Brass Incense Stand: BIS',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/incense holder/Brass Incense Holder/brh-5.jpg',
                        productType: ProductsTypes.BrassIncenseHolder,
                    },
                ]
            },
            {
                childTitle: 'Ceramic Incense Stand',
                childProducts: [
                    {
                        id: 1,
                        title: ' Ceramic Incense Stand',
                        details: 'Ceramic Incense Stand: CIS',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/incense holder/Ceramic Incense Holder/IMG-20200608-WA0029.jpg',
                        productType: ProductsTypes.CeramicIncenseHolder,
                    },
                    {
                        id: 2,
                        title: ' Ceramic Incense Stand',
                        details: 'Ceramic Incense Stand: CIS',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/incense holder/Ceramic Incense Holder/IMG-20200608-WA0030.jpg',
                        productType: ProductsTypes.CeramicIncenseHolder,
                    },
                    {
                        id: 3,
                        title: ' Ceramic Incense Stand',
                        details: 'Ceramic Incense Stand: CIS',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/incense holder/Ceramic Incense Holder/IMG-20200608-WA0031.jpg',
                        productType: ProductsTypes.CeramicIncenseHolder,
                    },
                ]
            },
            {
                childTitle: 'Metal Incense Stand',
                childProducts: [
                    {
                        id: 1,
                        title: ' Metal Incense Stand',
                        details: 'Metal Incense Stand: MIS',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/incense holder/Metal Incense Holder/AIH-1010.JPG',
                        productType: ProductsTypes.MetalIncenseHolder,
                    },
                    {
                        id: 2,
                        title: ' Metal Incense Stand',
                        details: 'Metal Incense Stand: MIS',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/incense holder/Metal Incense Holder/ALH-1009.jpg',
                        productType: ProductsTypes.MetalIncenseHolder,
                    },
                    {
                        id: 3,
                        title: ' Metal Incense Stand',
                        details: 'Metal Incense Stand: MIS',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/incense holder/Metal Incense Holder/ALH-1010.JPG',
                        productType: ProductsTypes.MetalIncenseHolder,
                    },
                    {
                        id: 4,
                        title: ' Metal Incense Stand',
                        details: 'Metal Incense Stand: MIS',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/incense holder/Metal Incense Holder/IMG_20191010_141854.jpg',
                        productType: ProductsTypes.MetalIncenseHolder,
                    },
                    {
                        id: 5,
                        title: ' Metal Incense Stand',
                        details: 'Metal Incense Stand: MIS',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/incense holder/Metal Incense Holder/IMG_20191010_141943.jpg',
                        productType: ProductsTypes.MetalIncenseHolder,
                    },
                    {
                        id: 6,
                        title: ' Metal Incense Stand',
                        details: 'Metal Incense Stand: MIS',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/incense holder/Metal Incense Holder/WMIH-35A.jpg',
                        productType: ProductsTypes.MetalIncenseHolder,
                    },
                    {
                        id: 7,
                        title: ' Metal Incense Stand',
                        details: 'Metal Incense Stand: MIS',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/incense holder/Metal Incense Holder/WMIH-35Ca.jpg',
                        productType: ProductsTypes.MetalIncenseHolder,
                    },
                ]
            },
            {
                childTitle: 'Paper Mache Incense Stand',
                childProducts: [
                    {
                        id: 1,
                        title: ' PaperMache Incense Stand',
                        details: 'PaperMache Incense Stand: PMIS',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/incense holder/Paper Mache Incense holder/PMSH-06.jpg',
                        productType: ProductsTypes.PaperMacheIncenseHolder,
                    },
                    {
                        id: 2,
                        title: ' PaperMache Incense Stand',
                        details: 'PaperMache Incense Stand: PMIS',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/incense holder/Paper Mache Incense holder/PMSH-11.JPG',
                        productType: ProductsTypes.PaperMacheIncenseHolder,
                    },
                    {
                        id: 3,
                        title: ' PaperMache Incense Stand',
                        details: 'PaperMache Incense Stand: PMIS',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/incense holder/Paper Mache Incense holder/PMSH-12JPEG.jpg',
                        productType: ProductsTypes.PaperMacheIncenseHolder,
                    },
                ]
            },
            {
                childTitle: 'Wooden Incense Stand',
                childProducts: [
                    {
                        id: 1,
                        title: ' Wooden Incense Stand',
                        details: 'Wooden Incense Stand: WIS',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/incense holder/Wooden Incense Holder/Colour Ins.Holder.JPG',
                        productType: ProductsTypes.WoodenIncenseHolder,
                    },
                    {
                        id: 2,
                        title: ' Wooden Incense Stand',
                        details: 'Wooden Incense Stand: WIS',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/incense holder/Wooden Incense Holder/WCB-01.jpg',
                        productType: ProductsTypes.WoodenIncenseHolder,
                    },
                    {
                        id: 3,
                        title: ' Wooden Incense Stand',
                        details: 'Wooden Incense Stand: WIS',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/incense holder/Wooden Incense Holder/WH-227.JPG',
                        productType: ProductsTypes.WoodenIncenseHolder,
                    },
                    {
                        id: 4,
                        title: ' Wooden Incense Stand',
                        details: 'Wooden Incense Stand: WIS',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/incense holder/Wooden Incense Holder/WH-230.JPG',
                        productType: ProductsTypes.WoodenIncenseHolder,
                    },
                    {
                        id: 5,
                        title: ' Wooden Incense Stand',
                        details: 'Wooden Incense Stand: WIS',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/incense holder/Wooden Incense Holder/WHC-02.jpg',
                        productType: ProductsTypes.WoodenIncenseHolder,
                    },
                    {
                        id: 6,
                        title: ' Wooden Incense Stand',
                        details: 'Wooden Incense Stand: WIS',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/incense holder/Wooden Incense Holder/WHC-05.jpg',
                        productType: ProductsTypes.WoodenIncenseHolder,
                    },
                    {
                        id: 7,
                        title: ' Wooden Incense Stand',
                        details: 'Wooden Incense Stand: WIS',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/incense holder/Wooden Incense Holder/WHC-06.jpg',
                        productType: ProductsTypes.WoodenIncenseHolder,
                    },
                    {
                        id: 8,
                        title: ' Wooden Incense Stand',
                        details: 'Wooden Incense Stand: WIS',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/incense holder/Wooden Incense Holder/Incense Holdr Papdi Wood.jpg',
                        productType: ProductsTypes.WoodenIncenseHolder,
                    },
                    {
                        id: 9,
                        title: ' Wooden Incense Stand',
                        details: 'Wooden Incense Stand: WIS',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/incense holder/Wooden Incense Holder/WIB-502.jpg',
                        productType: ProductsTypes.WoodenIncenseHolder,
                    },
                    {
                        id: 10,
                        title: ' Wooden Incense Stand',
                        details: 'Wooden Incense Stand: WIS',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/incense holder/Wooden Incense Holder/WIB-503.jpg',
                        productType: ProductsTypes.WoodenIncenseHolder,
                    },
                    {
                        id: 11,
                        title: ' Wooden Incense Stand',
                        details: 'Wooden Incense Stand: WIS',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/incense holder/Wooden Incense Holder/WIB-504.jpg',
                        productType: ProductsTypes.WoodenIncenseHolder,
                    },
                    {
                        id: 12,
                        title: ' Wooden Incense Stand',
                        details: 'Wooden Incense Stand: WIS',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/incense holder/Wooden Incense Holder/Wooden  Ins  Holder- WIH- C-03 Red.jpg',
                        productType: ProductsTypes.WoodenIncenseHolder,
                    },
                    {
                        id: 13,
                        title: ' Wooden Incense Stand',
                        details: 'Wooden Incense Stand: WIS',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/incense holder/Wooden Incense Holder/Wooden  Ins  Holder- WIH- C-03 Y.jpg',
                        productType: ProductsTypes.WoodenIncenseHolder,
                    },
                    {
                        id: 14,
                        title: ' Wooden Incense Stand',
                        details: 'Wooden Incense Stand: WIS',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/incense holder/Wooden Incense Holder/Wooden  Ins Boxr- WIB C-01.jpg',
                        productType: ProductsTypes.WoodenIncenseHolder,
                    },
                    {
                        id: 15,
                        title: ' Wooden Incense Stand',
                        details: 'Wooden Incense Stand: WIS',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/incense holder/Wooden Incense Holder/Wooden  Ins Boxr- WIB C-02.jpg',
                        productType: ProductsTypes.WoodenIncenseHolder,
                    },
                    {
                        id: 16,
                        title: ' Wooden Incense Stand',
                        details: 'Wooden Incense Stand: WIS',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/incense holder/Wooden Incense Holder/WH-220.JPG',
                        productType: ProductsTypes.WoodenIncenseHolder,
                    },
                    {
                        id: 17,
                        title: ' Wooden Incense Stand',
                        details: 'Wooden Incense Stand: WIS',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/incense holder/Wooden Incense Holder/WH-220A.JPG',
                        productType: ProductsTypes.WoodenIncenseHolder,
                    },
                    {
                        id: 18,
                        title: ' Wooden Incense Stand',
                        details: 'Wooden Incense Stand: WIS',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/incense holder/Wooden Incense Holder/wooden holder.jpg',
                        productType: ProductsTypes.WoodenIncenseHolder,
                    },
                    {
                        id: 19,
                        title: ' Wooden Incense Stand',
                        details: 'Wooden Incense Stand: WIS',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/incense holder/Wooden Incense Holder/Wooden Incense Holder Plain in  Shesham Polished.jpg',
                        productType: ProductsTypes.WoodenIncenseHolder,
                    },
                    {
                        id: 20,
                        title: ' Wooden Incense Stand',
                        details: 'Wooden Incense Stand: WIS',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/incense holder/Wooden Incense Holder/Wooden Incense Holder Plain in Natural finish.jpg',
                        productType: ProductsTypes.WoodenIncenseHolder,
                    },
                    

                ]

            }

        ]
    },

    {
        pageTitle: 'Oil Burner',
        pageProductType: ProductsTypes.OilBurner,
        children: [
            {
                childTitle: 'Brass Oil Burner',
                childProducts: [
                    {
                        id: 1,
                        title: ' Brass Oil Burner',
                        details: 'Brass Oil Burner: BOB',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/oil burner/Brass Oil Burner/BBA-10.JPG',
                        productType: ProductsTypes.BrassOilBurner,
                    },
                ]
            },
            {
                childTitle: 'Soft Stone Oil Burner',
                childProducts: [
                    {
                        id: 1,
                        title: 'Soft Stone Oil Burner',
                        details: 'Soft Stone Oil Burner: SSOB',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/oil burner/Soft Stone Oil Burner/BS-O1.JPG',
                        productType: ProductsTypes.SoftStoneOilBurner,
                    },
                    {
                        id: 2,
                        title: 'Soft Stone Oil Burner',
                        details: 'Soft Stone Oil Burner: SSOB',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/oil burner/Soft Stone Oil Burner/BS-OB-02.JPG',
                        productType: ProductsTypes.SoftStoneOilBurner,
                    },
                    {
                        id: 3,
                        title: 'Soft Stone Oil Burner',
                        details: 'Soft Stone Oil Burner: SSOB',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/oil burner/Soft Stone Oil Burner/BS-OB45.JPG',
                        productType: ProductsTypes.SoftStoneOilBurner,
                    },

                    {
                        id: 4,
                        title: 'Soft Stone Oil Burner',
                        details: 'Soft Stone Oil Burner: SSOB',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/oil burner/Soft Stone Oil Burner/BS-OB50.JPG',
                        productType: ProductsTypes.SoftStoneOilBurner,
                    },
                    {
                        id: 5,
                        title: ' Soft Stone Oil Burner',
                        details: 'Soft Stone Oil Burner: SSOB',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/oil burner/Soft Stone Oil Burner/BS-OB51.JPG',
                        productType: ProductsTypes.SoftStoneOilBurner,
                    },
                    {
                        id: 6,
                        title: ' Soft Stone Oil Burner',
                        details: 'Soft Stone Oil Burner: SSOB',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/oil burner/Soft Stone Oil Burner/L-052.jpg',
                        productType: ProductsTypes.SoftStoneOilBurner,
                    },
                    {
                        id: 7,
                        title: ' Soft Stone Oil Burner',
                        details: 'Soft Stone Oil Burner: SSOB',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/oil burner/Soft Stone Oil Burner/L-053-10.jpg',
                        productType: ProductsTypes.SoftStoneOilBurner,
                    },
                    {
                        id: 8,
                        title: ' Soft Stone Oil Burner',
                        details: 'Soft Stone Oil Burner: SSOB',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/oil burner/Soft Stone Oil Burner/L-53-11.jpg',
                        productType: ProductsTypes.SoftStoneOilBurner,
                    },
                    {
                        id: 9,
                        title: ' Soft Stone Oil Burner',
                        details: 'Soft Stone Oil Burner: SSOB',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/oil burner/Soft Stone Oil Burner/L-054-7.jpg',
                        productType: ProductsTypes.SoftStoneOilBurner,
                    },
                ]
            },
        ]
    },
    {
        pageTitle: 'Resin Burner',
        pageProductType: ProductsTypes.ResinBurner,
        children: [
            {
                childTitle: 'Brass Resin Burner',
                childProducts: [
                    {
                        id: 1,
                        title: 'Brass Resin Burner',
                        details: 'Brass Resin Burner: BRB',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/Resin Burner/Brass Resin Burner/1114.jpg',
                        productType: ProductsTypes.BrassResinBurner,
                    },
                    {
                        id: 2,
                        title: 'Brass Resin Burner',
                        details: 'Brass Resin Burner: BRB',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/Resin Burner/Brass Resin Burner/BRB-03 Blue.jpg',
                        productType: ProductsTypes.BrassResinBurner,
                    },
                    {
                        id: 3,
                        title: 'Brass Resin Burner',
                        details: 'Brass Resin Burner: BRB',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/Resin Burner/Brass Resin Burner/BRB-03G.jpg',
                        productType: ProductsTypes.BrassResinBurner,
                    },
                    {
                        id: 4,
                        title: 'Brass Resin Burner',
                        details: 'Brass Resin Burner: BRB',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/Resin Burner/Brass Resin Burner/BRB-03R.jpg',
                        productType: ProductsTypes.BrassResinBurner,
                    },
                    {
                        id: 5,
                        title: 'Brass Resin Burner',
                        details: 'Brass Resin Burner: BRB',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/Resin Burner/Brass Resin Burner/BRB-03T.jpg',
                        productType: ProductsTypes.BrassResinBurner,
                    },
                    {
                        id: 6,
                        title: 'Brass Resin Burner',
                        details: 'Brass Resin Burner: BRB',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/Resin Burner/Brass Resin Burner/BRB-101-Pentagram  Carved Charcoal Burner.JPG',
                        productType: ProductsTypes.BrassResinBurner,
                    },
                    {
                        id: 7,
                        title: 'Brass Resin Burner',
                        details: 'Brass Resin Burner: BRB',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/Resin Burner/Brass Resin Burner/BRB-102Triple Moon Carved Charcoal Burner.JPG',
                        productType: ProductsTypes.BrassResinBurner,
                    },
                    {
                        id: 8,
                        title: 'Brass Resin Burner',
                        details: 'Brass Resin Burner: BRB',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/Resin Burner/Brass Resin Burner/BRB03B.jpg',
                        productType: ProductsTypes.BrassResinBurner,
                    },
                ]
            },
            {
                childTitle: 'Wooden Resin Burner',
                childProducts: [
                    {
                        id: 1,
                        title: ' Wooden Resin Burner',
                        details: 'Wooden Resin Burner: WRB',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/Resin Burner/Brass Resin Burner/1114.jpg',
                        productType: ProductsTypes.WoodenResinBurner,
                    },
                ]
            }
        ]
    },
    {
        pageTitle: 'Tarot Box',
        pageProductType: ProductsTypes.TarotBox,
        children: [
            {
                childTitle: 'Tarot Box',
                childProducts: [
                    {
                        id: 1,
                        title: 'Tarot Box',
                        details: 'Tarot Box: TB',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/Tarot Box/BOX-03a.JPG',
                        productType: ProductsTypes.TarotBox,
                    },
                    {
                        id: 2,
                        title: 'Tarot Box',
                        details: 'Tarot Box: TB',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/Tarot Box/RCI -01.jpg',
                        productType: ProductsTypes.TarotBox,
                    },
                    {
                        id: 3,
                        title: 'Tarot Box',
                        details: 'Tarot Box: TB',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/Tarot Box/RCI-02.jpg',
                        productType: ProductsTypes.TarotBox,
                    },
                    {
                        id: 4,
                        title: 'Tarot Box',
                        details: 'Tarot Box: TB',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/Tarot Box/RCI-03.jpg',
                        productType: ProductsTypes.TarotBox,
                    },
                    {
                        id: 5,
                        title: 'Tarot Box',
                        details: 'Tarot Box: TB',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/Tarot Box/RCI-04.jpg',
                        productType: ProductsTypes.TarotBox,
                    },
                    {
                        id: 6,
                        title: 'Tarot Box',
                        details: 'Tarot Box: TB',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/Tarot Box/Tarot Box.jpg',
                        productType: ProductsTypes.TarotBox,
                    },
                ]
            }
        ]
    },
    {
        pageTitle: 'Cushion Covers',
        pageProductType: ProductsTypes.CushionCovers,
        children: [
            {
                childTitle: 'Cushion Covers',
                childProducts: [

                    {
                        id: 1,
                        title: 'Cushion Covers',
                        details: 'Cushion Covers: CC',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/Cushion Covers/IMG-20200629-WA0007.jpg',
                        productType: ProductsTypes.CushionCovers,
                    },
                    {
                        id: 2,
                        title: 'Cushion Covers',
                        details: 'Cushion Covers: CC',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/Cushion Covers/IMG-20200629-WA0013.jpg',
                        productType: ProductsTypes.CushionCovers,
                    },
                    {
                        id: 3,
                        title: 'Cushion Covers',
                        details: 'Cushion Covers: CC',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/Cushion Covers/IMG-20200629-WA0014.jpg',
                        productType: ProductsTypes.CushionCovers,
                    },
                    {
                        id: 4,
                        title: 'Cushion Covers',
                        details: 'Cushion Covers: CC',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/Cushion Covers/IMG-20200629-WA0020.jpg',
                        productType: ProductsTypes.CushionCovers,
                    },
                    {
                        id: 5,
                        title: 'Cushion Covers',
                        details: 'Cushion Covers: CC',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/Cushion Covers/IMG-20200629-WA0021.jpg',
                        productType: ProductsTypes.CushionCovers,
                    },
                    {
                        id: 6,
                        title: 'Cushion Covers',
                        details: 'Cushion Covers: CC',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/Cushion Covers/IMG-20200629-WA0022.jpg',
                        productType: ProductsTypes.CushionCovers,
                    },
                    {
                        id: 7,
                        title: 'Cushion Covers',
                        details: 'Cushion Covers: CC',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/Cushion Covers/IMG-20200629-WA0025.jpg',
                        productType: ProductsTypes.CushionCovers,
                    },
                    {
                        id: 8,
                        title: 'Cushion Covers',
                        details: 'Cushion Covers: CC',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/Cushion Covers/IMG-20200629-WA0026.jpg',
                        productType: ProductsTypes.CushionCovers,
                    },
                    {
                        id: 9,
                        title: 'Cushion Covers',
                        details: 'Cushion Covers: CC',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/Cushion Covers/IMG-20200629-WA0027.jpg',
                        productType: ProductsTypes.CushionCovers,
                    },
                    {
                        id: 10,
                        title: 'Cushion Covers',
                        details: 'Cushion Covers: CC',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/Cushion Covers/IMG-20200629-WA0029.jpg',
                        productType: ProductsTypes.CushionCovers,
                    },
                    {
                        id: 11,
                        title: 'Cushion Covers',
                        details: 'Cushion Covers: CC',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/Cushion Covers/IMG-20200629-WA0030.jpg',
                        productType: ProductsTypes.CushionCovers,
                    },
                    {
                        id: 12,
                        title: 'Cushion Covers',
                        details: 'Cushion Covers: CC',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/Cushion Covers/IMG-20200629-WA0031.jpg',
                        productType: ProductsTypes.CushionCovers,
                    },
                    {
                        id: 13,
                        title: 'Cushion Covers',
                        details: 'Cushion Covers: CC',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/Cushion Covers/IMG-20200629-WA0032.jpg',
                        productType: ProductsTypes.CushionCovers,
                    },
                    {
                        id: 14,
                        title: 'Cushion Covers',
                        details: 'Cushion Covers: CC',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/Cushion Covers/IMG-20200629-WA0033.jpg',
                        productType: ProductsTypes.CushionCovers,
                    },
                    {
                        id: 15,
                        title: 'Cushion Covers',
                        details: 'Cushion Covers: CC',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/Cushion Covers/IMG-20200629-WA0034.jpg',
                        productType: ProductsTypes.CushionCovers,
                    },
                    {
                        id: 16,
                        title: 'Cushion Covers',
                        details: 'Cushion Covers: CC',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/Cushion Covers/IMG-20200629-WA0036.jpg',
                        productType: ProductsTypes.CushionCovers,
                    },
                    {
                        id: 17,
                        title: 'Cushion Covers',
                        details: 'Cushion Covers: CC',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/Cushion Covers/IMG-20200629-WA0039.jpg',
                        productType: ProductsTypes.CushionCovers,
                    },
                    {
                        id: 18,
                        title: 'Cushion Covers',
                        details: 'Cushion Covers: CC',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/Cushion Covers/IMG-20200629-WA0046.jpg',
                        productType: ProductsTypes.CushionCovers,
                    },
                    {
                        id: 19,
                        title: 'Cushion Covers',
                        details: 'Cushion Covers: CC',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/Cushion Covers/IMG-20200629-WA0047.jpg',
                        productType: ProductsTypes.CushionCovers,
                    },
                    {
                        id: 20,
                        title: 'Cushion Covers',
                        details: 'Cushion Covers: CC',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/Cushion Covers/IMG-20200629-WA0048.jpg',
                        productType: ProductsTypes.CushionCovers,
                    },
                    {
                        id: 21,
                        title: 'Cushion Covers',
                        details: 'Cushion Covers: CC',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/Cushion Covers/IMG-20200629-WA0049.jpg',
                        productType: ProductsTypes.CushionCovers,
                    },
                    {
                        id: 22,
                        title: 'Cushion Covers',
                        details: 'Cushion Covers: CC',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/Cushion Covers/IMG-20200629-WA0050.jpg',
                        productType: ProductsTypes.CushionCovers,
                    },
                    {
                        id: 23,
                        title: 'Cushion Covers',
                        details: 'Cushion Covers: CC',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/Cushion Covers/IMG-20200629-WA0051.jpg',
                        productType: ProductsTypes.CushionCovers,
                    },
                    {
                        id: 24,
                        title: 'Cushion Covers',
                        details: 'Cushion Covers: CC',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/Cushion Covers/IMG-20200629-WA0052.jpg',
                        productType: ProductsTypes.CushionCovers,
                    },
                    {
                        id: 25,
                        title: 'Cushion Covers',
                        details: 'Cushion Covers: CC',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/Cushion Covers/IMG-20200629-WA0053.jpg',
                        productType: ProductsTypes.CushionCovers,
                    },
                   
                ]
            }
        ]
    },
    {
        pageTitle: 'Bolster Cover',
        pageProductType: ProductsTypes.BolstersCovers,
        children: [
            {
                childTitle: 'Bolster Cover',
                childProducts: [

                    {
                        id: 1,
                        title: 'Bolster Cover',
                        details: 'Bolster Cover: BC',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/Bolsters Cover/IMG-20200629-WA0009.jpg',
                        productType: ProductsTypes.BolstersCovers,
                    },
                    {
                        id: 2,
                        title: 'Bolster Cover',
                        details: 'Bolster Cover: BC',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/Bolsters Cover/IMG-20200629-WA0010.jpg',
                        productType: ProductsTypes.BolstersCovers,
                    },
                    {
                        id: 3,
                        title: 'Bolster Cover',
                        details: 'Bolster Cover: BC',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/Bolsters Cover/IMG-20200629-WA0011.jpg',
                        productType: ProductsTypes.BolstersCovers,
                    },
                    {
                        id: 4,
                        title: 'Bolster Cover',
                        details: 'Bolster Cover: BC',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/Bolsters Cover/IMG-20200629-WA0012.jpg',
                        productType: ProductsTypes.BolstersCovers,
                    },
                    {
                        id: 5,
                        title: 'Bolster Cover',
                        details: 'Bolster Cover: BC',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/Bolsters Cover/IMG-20200629-WA0015.jpg',
                        productType: ProductsTypes.BolstersCovers,
                    },
                    {
                        id: 6,
                        title: 'Bolster Cover',
                        details: 'Bolster Cover: BC',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/Bolsters Cover/IMG-20200629-WA0016.jpg',
                        productType: ProductsTypes.BolstersCovers,
                    },
                    {
                        id: 7,
                        title: 'Bolster Cover',
                        details: 'Bolster Cover: BC',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/Bolsters Cover/IMG-20200629-WA0019.jpg',
                        productType: ProductsTypes.BolstersCovers,
                    },
                    {
                        id: 8,
                        title: 'Bolster Cover',
                        details: 'Bolster Cover: BC',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/Bolsters Cover/IMG-20200629-WA0023.jpg',
                        productType: ProductsTypes.BolstersCovers,
                    },
                    {
                        id: 9,
                        title: 'Bolster Cover',
                        details: 'Bolster Cover: BC',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/Bolsters Cover/IMG-20200629-WA0024.jpg',
                        productType: ProductsTypes.BolstersCovers,
                    },
                    {
                        id: 10,
                        title: 'Bolster Cover',
                        details: 'Bolster Cover: BC',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/Bolsters Cover/IMG-20200629-WA0028.jpg',
                        productType: ProductsTypes.BolstersCovers,
                    },
                    {
                        id: 11,
                        title: 'Bolster Cover',
                        details: 'Bolster Cover: BC',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/Bolsters Cover/IMG-20200629-WA0035.jpg',
                        productType: ProductsTypes.BolstersCovers,
                    },
                    {
                        id: 12,
                        title: 'Bolster Cover',
                        details: 'Bolster Cover: BC',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/Bolsters Cover/IMG-20200629-WA0037.jpg',
                        productType: ProductsTypes.BolstersCovers,
                    },
                    {
                        id: 13,
                        title: 'Bolster Cover',
                        details: 'Bolster Cover: BC',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/Bolsters Cover/IMG-20200629-WA0038.jpg',
                        productType: ProductsTypes.BolstersCovers,
                    },
                    {
                        id: 14,
                        title: 'Bolster Cover',
                        details: 'Bolster Cover: BC',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/Bolsters Cover/IMG-20200629-WA0042.jpg',
                        productType: ProductsTypes.BolstersCovers,
                    },
                    {
                        id: 15,
                        title: 'Bolster Cover',
                        details: 'Bolster Cover: BC',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/Bolsters Cover/IMG-20200629-WA0044.jpg',
                        productType: ProductsTypes.BolstersCovers,
                    },
                ]
            }
        ]
    },
    {
        pageTitle: 'Rugs',
        pageProductType: ProductsTypes.Rugs,
        children: [
            {
                childTitle: 'Rugs',
                childProducts: [

                    {
                        id: 1,
                        title: 'Rugs',
                        details: 'Rugs: R',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/Rugs/IMG-20200629-WA0017.jpg',
                        productType: ProductsTypes.Rugs,
                    },
                    {
                        id: 2,
                        title: 'Rugs',
                        details: 'Rugs: R',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/Rugs/IMG-20200629-WA0041.jpg',
                        productType: ProductsTypes.Rugs,
                    },
                    {
                        id: 3,
                        title: 'Rugs',
                        details: 'Rugs: R',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/Rugs/IMG-20200629-WA0043.jpg',
                        productType: ProductsTypes.Rugs,
                    },
                    {
                        id: 4,
                        title: 'Rugs',
                        details: 'Rugs: R',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/Rugs/IMG-20200629-WA0045.jpg',
                        productType: ProductsTypes.Rugs,
                    },
                ]
            }
        ]
    },
    {
        pageTitle: 'Door Mat',
        pageProductType: ProductsTypes.DoorMat,
        children: [
            {
                childTitle: 'Door Mat',
                childProducts: [

                    {
                        id: 1,
                        title: 'Door Mat',
                        details: 'Door Mat: DM',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/Door Mat/IMG-20200629-WA0008.jpg',
                        productType: ProductsTypes.DoorMat,
                    },
                     {
                        id: 2,
                        title: 'Door Mat',
                        details: 'Door Mat: DM',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/Door Mat/IMG-20200629-WA0018.jpg',
                        productType: ProductsTypes.DoorMat,
                    },
                    {
                        id: 3,
                        title: 'Door Mat',
                        details: 'Door Mat: DM',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/Door Mat/IMG-20200629-WA0040.jpg',
                        productType: ProductsTypes.DoorMat,
                    },
                ]
            }
        ]
    },
    {
        pageTitle: 'Singing Bowl',
        pageProductType: ProductsTypes.SingingBowl,
        children: [
            {
                childTitle: 'Singing Bowl',
                childProducts: [

                    {
                        id: 1,
                        title: 'Singing Bowl',
                        details: 'Singing Bowl: SB',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/Singing Bowl/PicsArt_07-10-03.53.58.jpg',
                        productType: ProductsTypes.SingingBowl,
                    },
                    {
                        id: 2,
                        title: 'Singing Bowl',
                        details: 'Singing Bowl: SB',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/Singing Bowl/PicsArt_07-10-04.01.23.png',
                        productType: ProductsTypes.SingingBowl,
                    },
                    {
                        id: 3,
                        title: 'Singing Bowl',
                        details: 'Singing Bowl: SB',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/Singing Bowl/PicsArt_07-10-04.02.51.jpg',
                        productType: ProductsTypes.SingingBowl,
                    },
                    {
                        id: 4,
                        title: 'Singing Bowl',
                        details: 'Singing Bowl: SB',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/Singing Bowl/PicsArt_07-10-04.03.31.jpg',
                        productType: ProductsTypes.SingingBowl,
                    },
                    {
                        id: 5,
                        title: 'Singing Bowl',
                        details: 'Singing Bowl: SB',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/Singing Bowl/PicsArt_07-10-04.04.59.jpg',
                        productType: ProductsTypes.SingingBowl,
                    },
                    {
                        id: 6,
                        title: 'Singing Bowl',
                        details: 'Singing Bowl: SB',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/Singing Bowl/PicsArt_07-10-04.05.27.jpg',
                        productType: ProductsTypes.SingingBowl,
                    },
                    {
                        id: 7,
                        title: 'Singing Bowl',
                        details: 'Singing Bowl: SB',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/Singing Bowl/PicsArt_07-10-04.05.53.jpg',
                        productType: ProductsTypes.SingingBowl,
                    },
                    {
                        id: 8,
                        title: 'Singing Bowl',
                        details: 'Singing Bowl: SB',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/Singing Bowl/PicsArt_07-10-04.06.15.jpg',
                        productType: ProductsTypes.SingingBowl,
                    },
                    {
                        id: 9,
                        title: 'Singing Bowl',
                        details: 'Singing Bowl: SB',
                        isAddedToCart: false,
                        imageSrc: 'assets/images/Singing Bowl/PicsArt_07-10-04.06.36.jpg',
                        productType: ProductsTypes.SingingBowl,
                    },
                ]
            }
        ]
    }
]




// export var PRODUCTS: Product[] = [
//     {
//         id: 1,
//         title: 'Resin BackFlow Fountain',
//         details: 'fountain dhoop stand',
//         imageSrc: 'assets/images/BackFlow Fountain/Resin Fountain/71UgC3RX5JL._SL1500_.jpg',
//         isAddedToCart: false,
//         productType: ProductsTypes.ResinFountain,
//         isChild: true,
//         parentProductType: ProductsTypes.BackFlowFountain,
//     },
//     {
//         id: 2,
//         title: 'Resin BackFlow Fountain',
//         details: 'fountain dhoop stand',
//         isAddedToCart: false,
//         imageSrc: 'assets/images/BackFlow Fountain/Resin Fountain/71vTrBF1l1L._SL1258_.jpg',
//         productType: ProductsTypes.ResinFountain,
//         isChild: true,
//         parentProductType: ProductsTypes.BackFlowFountain,
//     },
//     {
//         id: 3,
//         title: 'Resin BackFlow Fountain',
//         details: 'fountain dhoop stand',
//         isAddedToCart: false,
//         imageSrc: 'assets/images/BackFlow Fountain/Resin Fountain/DSC06386.JPG',
//         productType: ProductsTypes.ResinFountain,
//         isChild: true,
//         parentProductType: ProductsTypes.BackFlowFountain,
//     },
//     {
//         id: 4,
//         title: 'Resin BackFlow Fountain',
//         isAddedToCart: false,
//         details: 'fountain dhoop stand',
//         imageSrc: 'assets/images/BackFlow Fountain/Resin Fountain/IMG-20180705-WA0008.jpg',
//         productType: ProductsTypes.ResinFountain,
//         isChild: true,
//         parentProductType: ProductsTypes.BackFlowFountain,
//     },
//     {
//         id: 5,
//         title: 'Resin BackFlow Fountain',
//         isAddedToCart: false,
//         details: 'fountain dhoop stand',
//         imageSrc: 'assets/images/BackFlow Fountain/Resin Fountain/IMG-20180705-WA0019.jpg',
//         productType: ProductsTypes.ResinFountain,
//         isChild: true,
//         parentProductType: ProductsTypes.BackFlowFountain,
//     },
//     {
//         id: 6,
//         title: 'Resin BackFlow Fountain',
//         details: 'fountain dhoop stand',
//         isAddedToCart: false,
//         imageSrc: 'assets/images/BackFlow Fountain/Resin Fountain/IMG-20180705-WA0022.jpg',
//         productType: ProductsTypes.ResinFountain,
//         isChild: true,
//         parentProductType: ProductsTypes.BackFlowFountain,
//     },
//     {
//         id: 7,
//         title: 'Resin BackFlow Fountain',
//         isAddedToCart: false,
//         details: 'fountain dhoop stand',
//         imageSrc: 'assets/images/BackFlow Fountain/Resin Fountain/IMG-20180705-WA0025.jpg',
//         productType: ProductsTypes.ResinFountain,
//         isChild: true,
//         parentProductType: ProductsTypes.BackFlowFountain,
//     },
//     {
//         id: 8,
//         title: 'Resin BackFlow Fountain',
//         isAddedToCart: false,
//         details: 'fountain dhoop stand',
//         imageSrc: 'assets/images/BackFlow Fountain/Resin Fountain/IMG-20180705-WA0027.jpg',
//         productType: ProductsTypes.ResinFountain,
//         isChild: true,
//         parentProductType: ProductsTypes.BackFlowFountain,
//     },
//     {
//         id: 9,
//         title: 'Ceramic BackFlow Fountain',
//         isAddedToCart: false,
//         details: 'fountain dhoop stand',
//         imageSrc: 'assets/images/BackFlow Fountain/Ceramic Fountain/IMG-20170907-WA0018 .jpg',
//         productType: ProductsTypes.CeramicFountain,
//         isChild: true,
//         parentProductType: ProductsTypes.BackFlowFountain,
//     },
//     {
//         id: 10,
//         title: 'Ceramic BackFlow Fountain',
//         isAddedToCart: false,
//         details: 'fountain dhoop stand',
//         imageSrc: 'assets/images/BackFlow Fountain/Ceramic Fountain/PicsArt_06-14-03.25.56.jpg',
//         productType: ProductsTypes.CeramicFountain,
//         isChild: true,
//         parentProductType: ProductsTypes.BackFlowFountain,
//     },
//     {
//         id: 11,
//         title: 'Ceramic BackFlow Fountain',
//         isAddedToCart: false,
//         details: 'fountain dhoop stand',
//         imageSrc: 'assets/images/BackFlow Fountain/Ceramic Fountain/PicsArt_06-14-03.46.12.jpg',
//         productType: ProductsTypes.CeramicFountain,
//         isChild: true,
//         parentProductType: ProductsTypes.BackFlowFountain,
//     },
//     {
//         id: 12,
//         title: 'Ceramic BackFlow Fountain',
//         isAddedToCart: false,
//         details: 'fountain dhoop stand',
//         imageSrc: 'assets/images/BackFlow Fountain/Ceramic Fountain/PicsArt_06-14-04.14.39.jpg',
//         productType: ProductsTypes.CeramicFountain,
//         isChild: true,
//         parentProductType: ProductsTypes.BackFlowFountain,
//     },
//     {
//         id: 13,
//         title: 'Ceramic BackFlow Fountain',
//         isAddedToCart: false,
//         details: 'fountain dhoop stand',
//         imageSrc: 'assets/images/BackFlow Fountain/Ceramic Fountain/PicsArt_06-14-05.00.19.jpg',
//         productType: ProductsTypes.CeramicFountain,
//         isChild: true,
//         parentProductType: ProductsTypes.BackFlowFountain,
//     },
//     {
//         id: 14,
//         title: 'Ceramic BackFlow Fountain',
//         isAddedToCart: false,
//         details: 'fountain dhoop stand',
//         imageSrc: 'assets/images/BackFlow Fountain/Ceramic Fountain/PicsArt_06-14-05.28.57.jpg',
//         productType: ProductsTypes.CeramicFountain,
//         isChild: true,
//         parentProductType: ProductsTypes.BackFlowFountain,
//     },
//     {
//         id: 15,
//         title: 'Ceramic BackFlow Fountain',
//         isAddedToCart: false,
//         details: 'fountain dhoop stand',
//         imageSrc: 'assets/images/BackFlow Fountain/Ceramic Fountain/PicsArt_06-14-06.25.24.jpg',
//         productType: ProductsTypes.CeramicFountain,
//         isChild: true,
//         parentProductType: ProductsTypes.BackFlowFountain,
//     },
//     {
//         id: 16,
//         title: 'Ceramic BackFlow Fountain',
//         isAddedToCart: false,
//         details: 'fountain dhoop stand',
//         imageSrc: 'assets/images/BackFlow Fountain/Ceramic Fountain/PicsArt_06-14-06.51.36.jpg',
//         productType: ProductsTypes.CeramicFountain,
//         isChild: true,
//         parentProductType: ProductsTypes.BackFlowFountain,
//     },
//     {
//         id: 17,
//         title: 'Ceramic BackFlow Fountain',
//         isAddedToCart: false,
//         details: 'fountain dhoop stand',
//         imageSrc: 'assets/images/BackFlow Fountain/Ceramic Fountain/IMG_20200614_180748.jpg',
//         productType: ProductsTypes.CeramicFountain,
//         isChild: true,
//         parentProductType: ProductsTypes.BackFlowFountain,
//     },
//     {
//         id: 18,
//         title: 'Ceramic BackFlow Fountain',
//         isAddedToCart: false,
//         details: 'fountain dhoop stand',
//         imageSrc: 'assets/images/BackFlow Fountain/Ceramic Fountain/PicsArt_06-14-08.44.10.jpg',
//         productType: ProductsTypes.CeramicFountain,
//         isChild: true,
//         parentProductType: ProductsTypes.BackFlowFountain,
//     },
//     {
//         id: 19,
//         title: 'Ceramic BackFlow Fountain',
//         isAddedToCart: false,
//         details: 'fountain dhoop stand',
//         imageSrc: 'assets/images/BackFlow Fountain/Ceramic Fountain/PicsArt_06-14-09.52.51.jpg',
//         productType: ProductsTypes.CeramicFountain,
//         isChild: true,
//         parentProductType: ProductsTypes.BackFlowFountain,
//     },
//     {
//         id: 20,
//         title: 'Cobra Stand',
//         isAddedToCart: false,
//         details: 'fountain dhoop stand',
//         imageSrc: 'assets/images/Cobra Stand/Cobra stand 2 Inc.jpg',
//         productType: ProductsTypes.CobraStand,
//         isChild: false,
//         parentProductType: ProductsTypes.CobraStand,
//     },
//     {
//         id: 21,
//         title: 'Copper Bottles',
//         isAddedToCart: false,
//         details: 'Copper Water Bottles',
//         imageSrc: 'assets/images/Copper Bottles/BS-CV-04- Diammond .png',
//         productType: ProductsTypes.CopperBottle,
//         isChild: false,
//         parentProductType: ProductsTypes.CopperBottle,
//     },
//     {
//         id: 22,
//         title: 'Copper Bottles',
//         isAddedToCart: false,
//         details: 'Copper Water Bottles',
//         imageSrc: 'assets/images/Copper Bottles/BS-CV-03 Hammed.png',
//         productType: ProductsTypes.CopperBottle,
//         isChild: false,
//         parentProductType: ProductsTypes.CopperBottle,
//     },
//     {
//         id: 23,
//         title: 'Copper Bottles',
//         isAddedToCart: false,
//         details: 'Copper Water Bottles',
//         imageSrc: 'assets/images/Copper Bottles/BS-CV-05 printed.png',
//         productType: ProductsTypes.CopperBottle,
//         isChild: false,
//         parentProductType: ProductsTypes.CopperBottle,
//     },
//     {
//         id: 24,
//         title: 'Copper Bottles',
//         isAddedToCart: false,
//         details: 'Copper Water Bottles',
//         imageSrc: 'assets/images/Copper Bottles/BS-CV-06 Printed.png',
//         productType: ProductsTypes.CopperBottle,
//         isChild: false,
//         parentProductType: ProductsTypes.CopperBottle,
//     },
//     {
//         id: 25,
//         title: 'Copper Bottles',
//         isAddedToCart: false,
//         details: 'Copper Water Bottles',
//         imageSrc: 'assets/images/Copper Bottles/BS-CV-07 Printed.png',
//         productType: ProductsTypes.CopperBottle,
//         isChild: false,
//         parentProductType: ProductsTypes.CopperBottle,
//     },
//     {
//         id: 26,
//         title: 'Copper Bottles',
//         isAddedToCart: false,
//         details: 'Copper Water Bottles',
//         imageSrc: 'assets/images/Copper Bottles/BS-CV-08 Printed.jpg',
//         productType: ProductsTypes.CopperBottle,
//         isChild: false,
//         parentProductType: ProductsTypes.CopperBottle,
//     },
//     {
//         id: 27,
//         title: 'Copper Bottles',
//         isAddedToCart: false,
//         details: 'Copper Water Bottles',
//         imageSrc: 'assets/images/Copper Bottles/BS-CV-09 printed.jpg',
//         productType: ProductsTypes.CopperBottle,
//         isChild: false,
//         parentProductType: ProductsTypes.CopperBottle,
//     },
//     {
//         id: 28,
//         title: 'Copper Bottles',
//         isAddedToCart: false,
//         details: 'Copper Water Bottles',
//         imageSrc: 'assets/images/Copper Bottles/BS-CV-10 Printed.jpg',
//         productType: ProductsTypes.CopperBottle,
//         isChild: false,
//         parentProductType: ProductsTypes.CopperBottle,
//     },
//     {
//         id: 29,
//         title: 'Copper Bottles',
//         isAddedToCart: false,
//         details: 'Copper Water Bottles',
//         imageSrc: 'assets/images/Copper Bottles/BS-CV-11 Printed.jpg',
//         productType: ProductsTypes.CopperBottle,
//         isChild: false,
//         parentProductType: ProductsTypes.CopperBottle,
//     },
//     {
//         id: 30,
//         title: ' Incense Holder',
//         isAddedToCart: false,
//         details: 'Brass Incense Holder',
//         imageSrc: 'assets/images/incense holder/Brass Incense Holder/Brh-1.JPG',
//         productType: ProductsTypes.BrassIncenseHolder,
//         isChild: true,
//         parentProductType: ProductsTypes.IncenseHolder,
//     },
//     {
//         id: 31,
//         title: ' Incense Holder',
//         isAddedToCart: false,
//         details: 'Brass Incense Holder',
//         imageSrc: 'assets/images/incense holder/Brass Incense Holder/BRH-02.jpg',
//         productType: ProductsTypes.BrassIncenseHolder,
//         isChild: true,
//         parentProductType: ProductsTypes.IncenseHolder,
//     },
//     {
//         id: 32,
//         title: ' Incense Holder',
//         isAddedToCart: false,
//         details: 'Brass Incense Holder',
//         imageSrc: 'assets/images/incense holder/Brass Incense Holder/brh-5.jpg',
//         productType: ProductsTypes.BrassIncenseHolder,
//         isChild: true,
//         parentProductType: ProductsTypes.IncenseHolder,
//     },
//     {
//         id: 33,
//         title: ' Incense Holder',
//         isAddedToCart: false,
//         details: 'Ceramic Incense Holder',
//         imageSrc: 'assets/images/incense holder/Ceramic Incense Holder/IMG-20200608-WA0029.jpg',
//         productType: ProductsTypes.CeramicIncenseHolder,
//         isChild: true,
//         parentProductType: ProductsTypes.IncenseHolder,
//     },
//     {
//         id: 34,
//         title: ' Incense Holder',
//         isAddedToCart: false,
//         details: 'Ceramic Incense Holder',
//         imageSrc: 'assets/images/incense holder/Ceramic Incense Holder/IMG-20200608-WA0030.jpg',
//         productType: ProductsTypes.CeramicIncenseHolder,
//         isChild: true,
//         parentProductType: ProductsTypes.IncenseHolder,
//     },
//     {
//         id: 35,
//         title: ' Incense Holder',
//         isAddedToCart: false,
//         details: 'Ceramic Incense Holder',
//         imageSrc: 'assets/images/incense holder/Ceramic Incense Holder/IMG-20200608-WA0031.jpg',
//         productType: ProductsTypes.CeramicIncenseHolder,
//         isChild: true,
//         parentProductType: ProductsTypes.IncenseHolder,
//     },
//     {
//         id: 36,
//         title: ' Incense Holder',
//         isAddedToCart: false,
//         details: 'Metal Incense Holder',
//         imageSrc: 'assets/images/incense holder/Metal Incense Holder/AIH-1010.JPG',
//         productType: ProductsTypes.MetalIncenseHolder,
//         isChild: true,
//         parentProductType: ProductsTypes.IncenseHolder,
//     },
//     {
//         id: 37,
//         title: ' Incense Holder',
//         isAddedToCart: false,
//         details: 'Metal Incense Holder',
//         imageSrc: 'assets/images/incense holder/Metal Incense Holder/ALH-1009.jpg',
//         productType: ProductsTypes.MetalIncenseHolder,
//         isChild: true,
//         parentProductType: ProductsTypes.IncenseHolder,
//     },
//     {
//         id: 38,
//         title: ' Incense Holder',
//         isAddedToCart: false,
//         details: 'Metal Incense Holder',
//         imageSrc: 'assets/images/incense holder/Metal Incense Holder/ALH-1010.JPG',
//         productType: ProductsTypes.MetalIncenseHolder,
//         isChild: true,
//         parentProductType: ProductsTypes.IncenseHolder,
//     },
//     {
//         id: 39,
//         title: ' Incense Holder',
//         isAddedToCart: false,
//         details: 'Metal Incense Holder',
//         imageSrc: 'assets/images/incense holder/Metal Incense Holder/IMG_20191010_141854.jpg',
//         productType: ProductsTypes.MetalIncenseHolder,
//         isChild: true,
//         parentProductType: ProductsTypes.IncenseHolder,
//     },
//     {
//         id: 40,
//         title: ' Incense Holder',
//         isAddedToCart: false,
//         details: 'Metal Incense Holder',
//         imageSrc: 'assets/images/incense holder/Metal Incense Holder/IMG_20191010_141943.jpg',
//         productType: ProductsTypes.MetalIncenseHolder,
//         isChild: true,
//         parentProductType: ProductsTypes.IncenseHolder,
//     },
//     {
//         id: 41,
//         title: ' Incense Holder',
//         isAddedToCart: false,
//         details: 'Metal Incense Holder',
//         imageSrc: 'assets/images/incense holder/Metal Incense Holder/WMIH-35A.jpg',
//         productType: ProductsTypes.MetalIncenseHolder,
//         isChild: true,
//         parentProductType: ProductsTypes.IncenseHolder,
//     },
//     {
//         id: 42,
//         title: ' Incense Holder',
//         isAddedToCart: false,
//         details: 'Metal Incense Holder',
//         imageSrc: 'assets/images/incense holder/Metal Incense Holder/WMIH-35Ca.jpg',
//         productType: ProductsTypes.MetalIncenseHolder,
//         isChild: true,
//         parentProductType: ProductsTypes.IncenseHolder,
//     },
//     {
//         id: 43,
//         title: ' Incense Holder',
//         isAddedToCart: false,
//         details: 'Paper Mache Incense Holder',
//         imageSrc: 'assets/images/incense holder/Paper Mache Incense holder/PMSH-06.jpg',
//         productType: ProductsTypes.PaperMacheIncenseHolder,
//         isChild: true,
//         parentProductType: ProductsTypes.IncenseHolder,
//     },
//     {
//         id: 44,
//         title: ' Incense Holder',
//         isAddedToCart: false,
//         details: 'Paper Mache Incense Holder',
//         imageSrc: 'assets/images/incense holder/Paper Mache Incense holder/PMSH-11.JPG',
//         productType: ProductsTypes.PaperMacheIncenseHolder,
//         isChild: true,
//         parentProductType: ProductsTypes.IncenseHolder,
//     },
//     {
//         id: 45,
//         title: ' Incense Holder',
//         isAddedToCart: false,
//         details: 'Paper Mache Incense Holder',
//         imageSrc: 'assets/images/incense holder/Paper Mache Incense holder/PMSH-12JPEG.jpg',
//         productType: ProductsTypes.PaperMacheIncenseHolder,
//         isChild: true,
//         parentProductType: ProductsTypes.IncenseHolder,
//     },
//     {
//         id: 46,
//         title: ' Incense Holder',
//         isAddedToCart: false,
//         details: 'Wooden Incense Holder',
//         imageSrc: 'assets/images/incense holder/Wooden Incense Holder/Colour Ins.Holder.JPG',
//         productType: ProductsTypes.WoodenIncenseHolder,
//         isChild: true,
//         parentProductType: ProductsTypes.IncenseHolder,
//     },
//     {
//         id: 47,
//         title: ' Incense Holder',
//         isAddedToCart: false,
//         details: 'Wooden Incense Holder',
//         imageSrc: 'assets/images/incense holder/Wooden Incense Holder/WCB-01.jpg',
//         productType: ProductsTypes.WoodenIncenseHolder,
//         isChild: true,
//         parentProductType: ProductsTypes.IncenseHolder,
//     },
//     {
//         id: 48,
//         title: ' Incense Holder',
//         isAddedToCart: false,
//         details: 'Wooden Incense Holder',
//         imageSrc: 'assets/images/incense holder/Wooden Incense Holder/WH-227.JPG',
//         productType: ProductsTypes.WoodenIncenseHolder,
//         isChild: true,
//         parentProductType: ProductsTypes.IncenseHolder,
//     },
//     {
//         id: 49,
//         title: ' Incense Holder',
//         isAddedToCart: false,
//         details: 'Wooden Incense Holder',
//         imageSrc: 'assets/images/incense holder/Wooden Incense Holder/WH-230.JPG',
//         productType: ProductsTypes.WoodenIncenseHolder,
//         isChild: true,
//         parentProductType: ProductsTypes.IncenseHolder,
//     },
//     {
//         id: 50,
//         title: ' Incense Holder',
//         isAddedToCart: false,
//         details: 'Wooden Incense Holder',
//         imageSrc: 'assets/images/incense holder/Wooden Incense Holder/WHC-02.jpg',
//         productType: ProductsTypes.WoodenIncenseHolder,
//         isChild: true,
//         parentProductType: ProductsTypes.IncenseHolder,
//     },
//     {
//         id: 51,
//         title: ' Incense Holder',
//         isAddedToCart: false,
//         details: 'Wooden Incense Holder',
//         imageSrc: 'assets/images/incense holder/Wooden Incense Holder/WHC-05.jpg',
//         productType: ProductsTypes.WoodenIncenseHolder,
//         isChild: true,
//         parentProductType: ProductsTypes.IncenseHolder,
//     },
//     {
//         id: 52,
//         title: ' Incense Holder',
//         isAddedToCart: false,
//         details: 'Wooden Incense Holder',
//         imageSrc: 'assets/images/incense holder/Wooden Incense Holder/WHC-06.jpg',
//         productType: ProductsTypes.WoodenIncenseHolder,
//         isChild: true,
//         parentProductType: ProductsTypes.IncenseHolder,
//     },
//     {
//         id: 53,
//         title: ' Incense Holder',
//         isAddedToCart: false,
//         details: 'Wooden Incense Holder',
//         imageSrc: 'assets/images/incense holder/Wooden Incense Holder/WIB-501.jpg',
//         productType: ProductsTypes.WoodenIncenseHolder,
//         isChild: true,
//         parentProductType: ProductsTypes.IncenseHolder,
//     },
//     {
//         id: 54,
//         title: ' Incense Holder',
//         isAddedToCart: false,
//         details: 'Wooden Incense Holder',
//         imageSrc: 'assets/images/incense holder/Wooden Incense Holder/WIB-502.jpg',
//         productType: ProductsTypes.WoodenIncenseHolder,
//         isChild: true,
//         parentProductType: ProductsTypes.IncenseHolder,
//     },
//     {
//         id: 55,
//         title: ' Incense Holder',
//         isAddedToCart: false,
//         details: 'Wooden Incense Holder',
//         imageSrc: 'assets/images/incense holder/Wooden Incense Holder/WIB-503.jpg',
//         productType: ProductsTypes.WoodenIncenseHolder,
//         isChild: true,
//         parentProductType: ProductsTypes.IncenseHolder,
//     },
//     {
//         id: 56,
//         title: ' Incense Holder',
//         isAddedToCart: false,
//         details: 'Wooden Incense Holder',
//         imageSrc: 'assets/images/incense holder/Wooden Incense Holder/WIB-504.jpg',
//         productType: ProductsTypes.WoodenIncenseHolder,
//         isChild: true,
//         parentProductType: ProductsTypes.IncenseHolder,
//     },
//     {
//         id: 57,
//         title: ' Incense Holder',
//         isAddedToCart: false,
//         details: 'Wooden Incense Holder',
//         imageSrc:
//             'assets/images/incense holder/Wooden Incense Holder/Wooden  Ins  Holder- WIH- C-03 Red.jpg',
//         productType: ProductsTypes.WoodenIncenseHolder,
//         isChild: true,
//         parentProductType: ProductsTypes.IncenseHolder,
//     },
//     {
//         id: 58,
//         title: ' Incense Holder',
//         isAddedToCart: false,
//         details: 'Wooden Incense Holder',
//         imageSrc:
//             'assets/images/incense holder/Wooden Incense Holder/Wooden  Ins  Holder- WIH- C-03 Y.jpg',
//         productType: ProductsTypes.WoodenIncenseHolder,
//         isChild: true,
//         parentProductType: ProductsTypes.IncenseHolder,
//     },
//     {
//         id: 59,
//         title: ' Incense Holder',
//         isAddedToCart: false,
//         details: 'Wooden Incense Holder',
//         imageSrc:
//             'assets/images/incense holder/Wooden Incense Holder/Wooden  Ins Boxr- WIB C-01.jpg',
//         productType: ProductsTypes.WoodenIncenseHolder,
//         isChild: true,
//         parentProductType: ProductsTypes.IncenseHolder,
//     },
//     {
//         id: 60,
//         title: ' Incense Holder',
//         isAddedToCart: false,
//         details: 'Wooden Incense Holder',
//         imageSrc:
//             'assets/images/incense holder/Wooden Incense Holder/Wooden  Ins Boxr- WIB C-02.jpg',
//         productType: ProductsTypes.WoodenIncenseHolder,
//         isChild: true,
//         parentProductType: ProductsTypes.IncenseHolder,
//     },
//     {
//         id: 61,
//         title: ' Oil Burner',
//         isAddedToCart: false,
//         details: 'Brass Oil Burner',
//         imageSrc: 'assets/images/oil burner/Brass Oil Burner/BBA-10.JPG',
//         productType: ProductsTypes.BrassOilBurner,
//         isChild: true,
//         parentProductType: ProductsTypes.OilBurner,
//     },
//     {
//         id: 61,
//         title: ' Oil Burner',
//         isAddedToCart: false,
//         details: 'Soft Stone Oil Burner',
//         imageSrc: 'assets/images/oil burner/Soft Stone Oil Burner/BS-O1.JPG',
//         productType: ProductsTypes.SoftStoneOilBurner,
//         isChild: true,
//         parentProductType: ProductsTypes.OilBurner,
//     },
//     {
//         id: 62,
//         title: ' Oil Burner',
//         isAddedToCart: false,
//         details: 'Soft Stone Oil Burner',
//         imageSrc: 'assets/images/oil burner/Soft Stone Oil Burner/BS-OB-02.JPG',
//         productType: ProductsTypes.SoftStoneOilBurner,
//         isChild: true,
//         parentProductType: ProductsTypes.OilBurner,
//     },
//     {
//         id: 63,
//         title: ' Oil Burner',
//         isAddedToCart: false,
//         details: 'Soft Stone Oil Burner',
//         imageSrc: 'assets/images/oil burner/Soft Stone Oil Burner/BS-OB45.JPG',
//         productType: ProductsTypes.SoftStoneOilBurner,
//         isChild: true,
//         parentProductType: ProductsTypes.OilBurner,
//     },
//     {
//         id: 64,
//         title: ' Oil Burner',
//         isAddedToCart: false,
//         details: 'Soft Stone Oil Burner',
//         imageSrc: 'assets/images/oil burner/Soft Stone Oil Burner/BS-OB50.JPG',
//         productType: ProductsTypes.SoftStoneOilBurner,
//         isChild: true,
//         parentProductType: ProductsTypes.OilBurner,
//     },
//     {
//         id: 65,
//         title: ' Oil Burner',
//         isAddedToCart: false,
//         details: 'Soft Stone Oil Burner',
//         imageSrc: 'assets/images/oil burner/Soft Stone Oil Burner/BS-OB51.JPG',
//         productType: ProductsTypes.SoftStoneOilBurner,
//         isChild: true,
//         parentProductType: ProductsTypes.OilBurner,
//     },
//     {
//         id: 66,
//         title: ' Oil Burner',
//         isAddedToCart: false,
//         details: 'Soft Stone Oil Burner',
//         imageSrc: 'assets/images/oil burner/Soft Stone Oil Burner/L-052.jpg',
//         productType: ProductsTypes.SoftStoneOilBurner,
//         isChild: true,
//         parentProductType: ProductsTypes.OilBurner,
//     },
//     {
//         id: 67,
//         title: ' Oil Burner',
//         isAddedToCart: false,
//         details: 'Soft Stone Oil Burner',
//         imageSrc: 'assets/images/oil burner/Soft Stone Oil Burner/L-053-10.jpg',
//         productType: ProductsTypes.SoftStoneOilBurner,
//         isChild: true,
//         parentProductType: ProductsTypes.OilBurner,
//     },
//     {
//         id: 68,
//         title: ' Oil Burner',
//         isAddedToCart: false,
//         details: 'Soft Stone Oil Burner',
//         imageSrc: 'assets/images/oil burner/Soft Stone Oil Burner/L-53-11.jpg',
//         productType: ProductsTypes.SoftStoneOilBurner,
//         isChild: true,
//         parentProductType: ProductsTypes.OilBurner,
//     },
//     {
//         id: 69,
//         title: ' Oil Burner',
//         isAddedToCart: false,
//         details: 'Soft Stone Oil Burner',
//         imageSrc: 'assets/images/oil burner/Soft Stone Oil Burner/L-054-7.jpg',
//         productType: ProductsTypes.SoftStoneOilBurner,
//         isChild: true,
//         parentProductType: ProductsTypes.OilBurner,
//     },
//     {
//         id: 70,
//         title: ' Resin Burner',
//         isAddedToCart: false,
//         details: 'Brass Resin Burner',
//         imageSrc: 'assets/images/Resin Burner/Brass Resin Burner/1114.jpg',
//         productType: ProductsTypes.BrassResinBurner,
//         isChild: true,
//         parentProductType: ProductsTypes.ResinBurner,
//     },
//     {
//         id: 71,
//         title: ' Resin Burner',
//         isAddedToCart: false,
//         details: 'Brass Resin Burner',
//         imageSrc: 'assets/images/Resin Burner/Brass Resin Burner/BRB-03 Blue.jpg',
//         productType: ProductsTypes.BrassResinBurner,
//         isChild: true,
//         parentProductType: ProductsTypes.ResinBurner,
//     },
//     {
//         id: 72,
//         title: ' Resin Burner',
//         isAddedToCart: false,
//         details: 'Brass Resin Burner',
//         imageSrc: 'assets/images/Resin Burner/Brass Resin Burner/BRB-03G.jpg',
//         productType: ProductsTypes.BrassResinBurner,
//         isChild: true,
//         parentProductType: ProductsTypes.ResinBurner,
//     },
//     {
//         id: 73,
//         title: ' Resin Burner',
//         isAddedToCart: false,
//         details: 'Brass Resin Burner',
//         imageSrc: 'assets/images/Resin Burner/Brass Resin Burner/BRB-03R.jpg',
//         productType: ProductsTypes.BrassResinBurner,
//         isChild: true,
//         parentProductType: ProductsTypes.ResinBurner,
//     },
//     {
//         id: 74,
//         title: ' Resin Burner',
//         isAddedToCart: false,
//         details: 'Brass Resin Burner',
//         imageSrc: 'assets/images/Resin Burner/Brass Resin Burner/BRB-03T.jpg',
//         productType: ProductsTypes.BrassResinBurner,
//         isChild: true,
//         parentProductType: ProductsTypes.ResinBurner,
//     },
//     {
//         id: 75,
//         title: ' Resin Burner',
//         isAddedToCart: false,
//         details: 'Brass Resin Burner',
//         imageSrc:
//             'assets/images/Resin Burner/Brass Resin Burner/BRB-101-Pentagram  Carved Charcoal Burner.JPG',
//         productType: ProductsTypes.BrassResinBurner,
//         isChild: true,
//         parentProductType: ProductsTypes.ResinBurner,
//     },
//     {
//         id: 76,
//         title: ' Resin Burner',
//         isAddedToCart: false,
//         details: 'Brass Resin Burner',
//         imageSrc:
//             'assets/images/Resin Burner/Brass Resin Burner/BRB-102Triple Moon Carved Charcoal Burner.JPG',
//         productType: ProductsTypes.BrassResinBurner,
//         isChild: true,
//         parentProductType: ProductsTypes.ResinBurner,
//     },
//     {
//         id: 77,
//         title: ' Resin Burner',
//         isAddedToCart: false,
//         details: 'Brass Resin Burner',
//         imageSrc: 'assets/images/Resin Burner/Brass Resin Burner/BRB03B.jpg',
//         productType: ProductsTypes.BrassResinBurner,
//         isChild: true,
//         parentProductType: ProductsTypes.ResinBurner,
//     },
//     {
//         id: 78,
//         title: 'Tarot Box',
//         isAddedToCart: false,
//         details: 'Tarot Box',
//         imageSrc: 'assets/images/Tarot Box/BOX-03a.JPG',
//         productType: ProductsTypes.TarotBox,
//         isChild: false,
//         parentProductType: ProductsTypes.TarotBox,
//     },
//     {
//         id: 79,
//         title: 'Tarot Box',
//         isAddedToCart: false,
//         details: 'Tarot Box',
//         imageSrc: 'assets/images/Tarot Box/RCI -01.jpg',
//         productType: ProductsTypes.TarotBox,
//         isChild: false,
//         parentProductType: ProductsTypes.TarotBox,
//     },
//     {
//         id: 80,
//         title: 'Tarot Box',
//         isAddedToCart: false,
//         details: 'Tarot Box',
//         imageSrc: 'assets/images/Tarot Box/RCI-02.jpg',
//         productType: ProductsTypes.TarotBox,
//         isChild: false,
//         parentProductType: ProductsTypes.TarotBox,
//     },
//     {
//         id: 81,
//         title: 'Tarot Box',
//         isAddedToCart: false,
//         details: 'Tarot Box',
//         imageSrc: 'assets/images/Tarot Box/RCI-03.jpg',
//         productType: ProductsTypes.TarotBox,
//         isChild: false,
//         parentProductType: ProductsTypes.TarotBox,
//     },
//     {
//         id: 82,
//         title: 'Tarot Box',
//         isAddedToCart: false,
//         details: 'Tarot Box',
//         imageSrc: 'assets/images/Tarot Box/RCI-04.jpg',
//         productType: ProductsTypes.TarotBox,
//         isChild: false,
//         parentProductType: ProductsTypes.TarotBox,
//     },
//     {
//         id: 83,
//         title: 'Tarot Box',
//         isAddedToCart: false,
//         details: 'Tarot Box',
//         imageSrc: 'assets/images/Tarot Box/Tarot Box.jpg',
//         productType: ProductsTypes.TarotBox,
//         isChild: false,
//         parentProductType: ProductsTypes.TarotBox,
//     },
//     // {
//     //     id: 84,
//     //     title: 'Tarot Box',isAddedToCart:false,
//     //     details:  'Tarot Box',
//     //     imageSrc: 'assets/images/Tarot Box/Tree of Life.tiff',
//     //     productType:ProductsTypes.TarotBox,isChild:false,parentProductType:ProductsTypes.ResinBurner,
//     // },
// ];


// export var PARENTPRODUCTSTYPES: ParentProducts[] = [
//     { title: "Backflow fountain", parentProductType: ProductsTypes.BackFlowFountain },
//     { title: "Incense Holder", parentProductType: ProductsTypes.IncenseHolder},
//     { title: "Oil Burner", parentProductType: ProductsTypes.OilBurner},
//     { title: "Resin Burner", parentProductType: ProductsTypes.ResinBurner},
//     { title: "Cobra Stand", parentProductType: ProductsTypes.CobraStand},
//     { title: "Tarot Box", parentProductType: ProductsTypes.TarotBox},
//     { title: "Copper Bottles", parentProductType: ProductsTypes.CopperBottle},
// ]

// export var CHILDPRODUCTSTYPES: ParentProducts[] = [
//     { title: "Resin Fountain", parentProductType: ProductsTypes.ResinFountain},
//     { title: "Ceramic Fountain", parentProductType: ProductsTypes.CeramicFountain },
//     { title: "Metal Incense Holder", parentProductType: ProductsTypes.MetalIncenseHolder },
//     { title: "Wooden Incense Holder", parentProductType: ProductsTypes.WoodenIncenseHolder },
//     { title: "Ceramic Incense Holder", parentProductType: ProductsTypes.CeramicIncenseHolder },
//     { title: "Brass Incense Holder", parentProductType: ProductsTypes.BrassIncenseHolder },
//     { title: "Paper Mache Incense Holder", parentProductType: ProductsTypes.PaperMacheIncenseHolder },
//     { title: "Brass Oil Burner", parentProductType: ProductsTypes.BrassOilBurner },
//     { title: "Soft Stone Oil Burner", parentProductType: ProductsTypes.SoftStoneOilBurner },
//     { title: "Brass Resin Burner", parentProductType: ProductsTypes.BrassResinBurner },
//     { title: "Wooden Resin Burner", parentProductType: ProductsTypes.WoodenResinBurner },
//     { title: "Cobra Stand", parentProductType: ProductsTypes.CobraStand},
//     { title: "Tarot Box", parentProductType: ProductsTypes.TarotBox},
//     { title: "Copper Bottles", parentProductType: ProductsTypes.CopperBottle},

// ]